#ifndef CHART_OVERRIDE_H
#define CHART_OVERRIDE_H

#include "bn_array.h"
#include "bn_keypad.h"
#include "songs.h"

namespace songs
{
    
    #define JOAN_OVERRIDE
    constexpr bn::array<note_data, 160> joan_data = {{
        {bn::keypad::key_type::A, 32, 1},
        {bn::keypad::key_type::L, 36, 1},
        {bn::keypad::key_type::R, 40, 1},
        {bn::keypad::key_type::L, 44, 1},
        {bn::keypad::key_type::A, 48, 1},
        {bn::keypad::key_type::L, 52, 1},
        {bn::keypad::key_type::R, 56, 1},
        {bn::keypad::key_type::L, 60, 1},
        {bn::keypad::key_type::A, 64, 1},
        {bn::keypad::key_type::L, 68, 1},
        {bn::keypad::key_type::R, 72, 1},
        {bn::keypad::key_type::L, 76, 1},
        {bn::keypad::key_type::A, 80, 1},
        {bn::keypad::key_type::L, 84, 1},
        {bn::keypad::key_type::R, 88, 1},
        {bn::keypad::key_type::L, 92, 1},
        {bn::keypad::key_type::A, 96, 1},
        {bn::keypad::key_type::L, 100, 1},
        {bn::keypad::key_type::R, 104, 1},
        {bn::keypad::key_type::L, 108, 1},
        {bn::keypad::key_type::A, 112, 1},
        {bn::keypad::key_type::L, 116, 1},
        {bn::keypad::key_type::R, 120, 1},
        {bn::keypad::key_type::L, 124, 1},
        {bn::keypad::key_type::A, 128, 1},
        {bn::keypad::key_type::L, 132, 1},
        {bn::keypad::key_type::R, 136, 1},
        {bn::keypad::key_type::L, 140, 1},
        {bn::keypad::key_type::A, 144, 1},
        {bn::keypad::key_type::L, 148, 1},
        {bn::keypad::key_type::R, 152, 1},
        {bn::keypad::key_type::L, 156, 1},
        {bn::keypad::key_type::B, 160, 1},
        {bn::keypad::key_type::L, 164, 1},
        {bn::keypad::key_type::R, 168, 1},
        {bn::keypad::key_type::L, 172, 1},
        {bn::keypad::key_type::A, 176, 1},
        {bn::keypad::key_type::L, 180, 1},
        {bn::keypad::key_type::R, 184, 1},
        {bn::keypad::key_type::L, 188, 1},
        {bn::keypad::key_type::B, 192, 1},
        {bn::keypad::key_type::L, 196, 1},
        {bn::keypad::key_type::R, 200, 1},
        {bn::keypad::key_type::L, 204, 1},
        {bn::keypad::key_type::A, 208, 1},
        {bn::keypad::key_type::L, 212, 1},
        {bn::keypad::key_type::R, 216, 1},
        {bn::keypad::key_type::L, 220, 1},
        {bn::keypad::key_type::A, 224, 1},
        {bn::keypad::key_type::L, 228, 1},
        {bn::keypad::key_type::R, 232, 1},
        {bn::keypad::key_type::L, 236, 1},
        {bn::keypad::key_type::A, 240, 1},
        {bn::keypad::key_type::L, 244, 1},
        {bn::keypad::key_type::R, 248, 1},
        {bn::keypad::key_type::L, 252, 1},
        {bn::keypad::key_type::A, 256, 1},
        {bn::keypad::key_type::L, 260, 1},
        {bn::keypad::key_type::R, 264, 1},
        {bn::keypad::key_type::L, 268, 1},
        {bn::keypad::key_type::A, 272, 1},
        {bn::keypad::key_type::L, 276, 1},
        {bn::keypad::key_type::R, 280, 1},
        {bn::keypad::key_type::L, 284, 1},
        {bn::keypad::key_type::B, 288, 1},
        {bn::keypad::key_type::L, 292, 1},
        {bn::keypad::key_type::R, 296, 1},
        {bn::keypad::key_type::L, 300, 1},
        {bn::keypad::key_type::A, 304, 1},
        {bn::keypad::key_type::L, 308, 1},
        {bn::keypad::key_type::R, 312, 1},
        {bn::keypad::key_type::L, 316, 1},
        {bn::keypad::key_type::B, 320, 1},
        {bn::keypad::key_type::L, 324, 1},
        {bn::keypad::key_type::R, 328, 1},
        {bn::keypad::key_type::L, 332, 1},
        {bn::keypad::key_type::A, 336, 1},
        {bn::keypad::key_type::L, 340, 1},
        {bn::keypad::key_type::R, 344, 1},
        {bn::keypad::key_type::L, 348, 1},
        {bn::keypad::key_type::A, 352, 1},
        {bn::keypad::key_type::A, 356, 1},
        {bn::keypad::key_type::DOWN, 360, 1},
        {bn::keypad::key_type::R, 364, 1},
        {bn::keypad::key_type::DOWN, 368, 1},
        {bn::keypad::key_type::DOWN, 372, 1},
        {bn::keypad::key_type::L, 376, 1},
        {bn::keypad::key_type::R, 380, 1},
        {bn::keypad::key_type::B, 384, 1},
        {bn::keypad::key_type::A, 388, 1},
        {bn::keypad::key_type::L, 392, 1},
        {bn::keypad::key_type::A, 396, 1},
        {bn::keypad::key_type::R, 400, 1},
        {bn::keypad::key_type::A, 404, 1},
        {bn::keypad::key_type::DOWN, 408, 1},
        {bn::keypad::key_type::R, 412, 1},
        {bn::keypad::key_type::A, 416, 1},
        {bn::keypad::key_type::A, 420, 1},
        {bn::keypad::key_type::DOWN, 424, 1},
        {bn::keypad::key_type::R, 428, 1},
        {bn::keypad::key_type::DOWN, 432, 1},
        {bn::keypad::key_type::DOWN, 436, 1},
        {bn::keypad::key_type::L, 440, 1},
        {bn::keypad::key_type::R, 444, 1},
        {bn::keypad::key_type::B, 448, 1},
        {bn::keypad::key_type::A, 452, 1},
        {bn::keypad::key_type::L, 456, 1},
        {bn::keypad::key_type::A, 460, 1},
        {bn::keypad::key_type::R, 464, 1},
        {bn::keypad::key_type::A, 468, 1},
        {bn::keypad::key_type::DOWN, 472, 1},
        {bn::keypad::key_type::R, 476, 1},
        {bn::keypad::key_type::A, 480, 1},
        {bn::keypad::key_type::A, 484, 1},
        {bn::keypad::key_type::DOWN, 488, 1},
        {bn::keypad::key_type::R, 492, 1},
        {bn::keypad::key_type::DOWN, 496, 1},
        {bn::keypad::key_type::DOWN, 500, 1},
        {bn::keypad::key_type::L, 504, 1},
        {bn::keypad::key_type::R, 508, 1},
        {bn::keypad::key_type::B, 512, 1},
        {bn::keypad::key_type::A, 516, 1},
        {bn::keypad::key_type::L, 520, 1},
        {bn::keypad::key_type::A, 524, 1},
        {bn::keypad::key_type::R, 528, 1},
        {bn::keypad::key_type::A, 532, 1},
        {bn::keypad::key_type::DOWN, 536, 1},
        {bn::keypad::key_type::R, 540, 1},
        {bn::keypad::key_type::A, 544, 1},
        {bn::keypad::key_type::A, 548, 1},
        {bn::keypad::key_type::DOWN, 552, 1},
        {bn::keypad::key_type::R, 556, 1},
        {bn::keypad::key_type::DOWN, 560, 1},
        {bn::keypad::key_type::DOWN, 564, 1},
        {bn::keypad::key_type::L, 568, 1},
        {bn::keypad::key_type::R, 572, 1},
        {bn::keypad::key_type::B, 576, 1},
        {bn::keypad::key_type::A, 580, 1},
        {bn::keypad::key_type::L, 584, 1},
        {bn::keypad::key_type::A, 588, 1},
        {bn::keypad::key_type::R, 592, 1},
        {bn::keypad::key_type::A, 596, 1},
        {bn::keypad::key_type::DOWN, 600, 1},
        {bn::keypad::key_type::R, 604, 1},
        {bn::keypad::key_type::A, 608, 1},
        {bn::keypad::key_type::L, 612, 1},
        {bn::keypad::key_type::R, 616, 1},
        {bn::keypad::key_type::L, 620, 1},
        {bn::keypad::key_type::A, 624, 1},
        {bn::keypad::key_type::L, 628, 1},
        {bn::keypad::key_type::R, 632, 1},
        {bn::keypad::key_type::L, 636, 1},
        {bn::keypad::key_type::A, 640, 1},
        {bn::keypad::key_type::L, 644, 1},
        {bn::keypad::key_type::R, 648, 1},
        {bn::keypad::key_type::L, 652, 1},
        {bn::keypad::key_type::A, 656, 1},
        {bn::keypad::key_type::L, 660, 1},
        {bn::keypad::key_type::R, 664, 1},
        {bn::keypad::key_type::L, 668, 1}
    }};

    constexpr bn::array<int, 11> joan_pattern_lengths = {{
        32,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64
    }};

    constexpr song joan = {
        joan_data.data(),
        joan_data.size(),
        joan_pattern_lengths.data(),
        120,
        "Joan",
        normal,
        0,
        bn::music_items::a_joan
    };

    //#define A_NEW_ERA_OVERRIDE
    //constexpr bn::array<note_data, 298> a_new_era_data = {{
    //    {bn::keypad::key_type::A, 32, 1},
    //    {bn::keypad::key_type::A, 40, 1},
    //    {bn::keypad::key_type::R, 45, 1},
    //    {bn::keypad::key_type::A, 48, 1},
    //    {bn::keypad::key_type::A, 56, 1},
    //    {bn::keypad::key_type::DOWN, 56, 1},
    //    {bn::keypad::key_type::A, 64, 1},
    //    {bn::keypad::key_type::R, 69, 1},
    //    {bn::keypad::key_type::A, 72, 1},
    //    {bn::keypad::key_type::A, 80, 1},
    //    {bn::keypad::key_type::A, 88, 1},
    //    {bn::keypad::key_type::R, 93, 1},
    //    {bn::keypad::key_type::A, 96, 1},
    //    {bn::keypad::key_type::A, 104, 1},
    //    {bn::keypad::key_type::B, 104, 1},
    //    {bn::keypad::key_type::A, 112, 1},
    //    {bn::keypad::key_type::R, 112, 1},
    //    {bn::keypad::key_type::A, 120, 1},
    //    {bn::keypad::key_type::DOWN, 120, 1},
    //    {bn::keypad::key_type::B, 128, 1},
    //    {bn::keypad::key_type::A, 128, 1},
    //    {bn::keypad::key_type::B, 136, 1},
    //    {bn::keypad::key_type::R, 141, 1},
    //    {bn::keypad::key_type::B, 144, 1},
    //    {bn::keypad::key_type::B, 152, 1},
    //    {bn::keypad::key_type::DOWN, 152, 1},
    //    {bn::keypad::key_type::B, 160, 1},
    //    {bn::keypad::key_type::R, 165, 1},
    //    {bn::keypad::key_type::B, 168, 1},
    //    {bn::keypad::key_type::B, 176, 1},
    //    {bn::keypad::key_type::A, 176, 1},
    //    {bn::keypad::key_type::B, 184, 1},
    //    {bn::keypad::key_type::R, 189, 1},
    //    {bn::keypad::key_type::B, 192, 1},
    //    {bn::keypad::key_type::B, 200, 1},
    //    {bn::keypad::key_type::RIGHT, 200, 1},
    //    {bn::keypad::key_type::B, 208, 1},
    //    {bn::keypad::key_type::A, 213, 1},
    //    {bn::keypad::key_type::B, 216, 1},
    //    {bn::keypad::key_type::A, 224, 1},
    //    {bn::keypad::key_type::A, 232, 1},
    //    {bn::keypad::key_type::R, 237, 1},
    //    {bn::keypad::key_type::A, 240, 1},
    //    {bn::keypad::key_type::A, 248, 1},
    //    {bn::keypad::key_type::DOWN, 248, 1},
    //    {bn::keypad::key_type::A, 256, 1},
    //    {bn::keypad::key_type::R, 261, 1},
    //    {bn::keypad::key_type::A, 264, 1},
    //    {bn::keypad::key_type::A, 272, 1},
    //    {bn::keypad::key_type::A, 280, 1},
    //    {bn::keypad::key_type::R, 285, 1},
    //    {bn::keypad::key_type::A, 288, 1},
    //    {bn::keypad::key_type::A, 296, 1},
    //    {bn::keypad::key_type::B, 296, 1},
    //    {bn::keypad::key_type::A, 304, 1},
    //    {bn::keypad::key_type::R, 304, 1},
    //    {bn::keypad::key_type::A, 312, 1},
    //    {bn::keypad::key_type::DOWN, 312, 1},
    //    {bn::keypad::key_type::B, 320, 1},
    //    {bn::keypad::key_type::A, 320, 1},
    //    {bn::keypad::key_type::B, 328, 1},
    //    {bn::keypad::key_type::R, 333, 1},
    //    {bn::keypad::key_type::B, 336, 1},
    //    {bn::keypad::key_type::B, 344, 1},
    //    {bn::keypad::key_type::DOWN, 344, 1},
    //    {bn::keypad::key_type::B, 352, 1},
    //    {bn::keypad::key_type::R, 357, 1},
    //    {bn::keypad::key_type::B, 360, 1},
    //    {bn::keypad::key_type::B, 368, 1},
    //    {bn::keypad::key_type::A, 368, 1},
    //    {bn::keypad::key_type::B, 376, 1},
    //    {bn::keypad::key_type::R, 381, 1},
    //    {bn::keypad::key_type::B, 384, 1},
    //    {bn::keypad::key_type::B, 392, 1},
    //    {bn::keypad::key_type::RIGHT, 392, 1},
    //    {bn::keypad::key_type::B, 400, 1},
    //    {bn::keypad::key_type::A, 405, 1},
    //    {bn::keypad::key_type::B, 408, 1},
    //    {bn::keypad::key_type::DOWN, 416, 1},
    //    {bn::keypad::key_type::L, 416, 1},
    //    {bn::keypad::key_type::DOWN, 424, 1},
    //    {bn::keypad::key_type::L, 429, 1},
    //    {bn::keypad::key_type::DOWN, 432, 1},
    //    {bn::keypad::key_type::DOWN, 440, 1},
    //    {bn::keypad::key_type::L, 440, 1},
    //    {bn::keypad::key_type::DOWN, 448, 1},
    //    {bn::keypad::key_type::L, 453, 1},
    //    {bn::keypad::key_type::DOWN, 456, 1},
    //    {bn::keypad::key_type::R, 464, 1},
    //    {bn::keypad::key_type::L, 464, 1},
    //    {bn::keypad::key_type::R, 472, 1},
    //    {bn::keypad::key_type::L, 477, 1},
    //    {bn::keypad::key_type::R, 480, 1},
    //    {bn::keypad::key_type::R, 488, 1},
    //    {bn::keypad::key_type::L, 488, 1},
    //    {bn::keypad::key_type::R, 496, 1},
    //    {bn::keypad::key_type::L, 501, 1},
    //    {bn::keypad::key_type::R, 504, 1},
    //    {bn::keypad::key_type::B, 512, 1},
    //    {bn::keypad::key_type::UP, 512, 1},
    //    {bn::keypad::key_type::B, 520, 1},
    //    {bn::keypad::key_type::A, 525, 1},
    //    {bn::keypad::key_type::B, 528, 1},
    //    {bn::keypad::key_type::B, 536, 1},
    //    {bn::keypad::key_type::UP, 536, 1},
    //    {bn::keypad::key_type::B, 544, 1},
    //    {bn::keypad::key_type::RIGHT, 549, 1},
    //    {bn::keypad::key_type::B, 552, 1},
    //    {bn::keypad::key_type::B, 560, 1},
    //    {bn::keypad::key_type::A, 560, 1},
    //    {bn::keypad::key_type::A, 608, 1},
    //    {bn::keypad::key_type::A, 616, 1},
    //    {bn::keypad::key_type::R, 621, 1},
    //    {bn::keypad::key_type::A, 624, 1},
    //    {bn::keypad::key_type::A, 632, 1},
    //    {bn::keypad::key_type::DOWN, 632, 1},
    //    {bn::keypad::key_type::A, 640, 1},
    //    {bn::keypad::key_type::R, 645, 1},
    //    {bn::keypad::key_type::A, 648, 1},
    //    {bn::keypad::key_type::A, 656, 1},
    //    {bn::keypad::key_type::A, 664, 1},
    //    {bn::keypad::key_type::R, 669, 1},
    //    {bn::keypad::key_type::A, 672, 1},
    //    {bn::keypad::key_type::A, 680, 1},
    //    {bn::keypad::key_type::B, 680, 1},
    //    {bn::keypad::key_type::A, 688, 1},
    //    {bn::keypad::key_type::R, 688, 1},
    //    {bn::keypad::key_type::A, 696, 1},
    //    {bn::keypad::key_type::DOWN, 696, 1},
    //    {bn::keypad::key_type::B, 704, 1},
    //    {bn::keypad::key_type::A, 704, 1},
    //    {bn::keypad::key_type::B, 712, 1},
    //    {bn::keypad::key_type::R, 717, 1},
    //    {bn::keypad::key_type::B, 720, 1},
    //    {bn::keypad::key_type::B, 728, 1},
    //    {bn::keypad::key_type::DOWN, 728, 1},
    //    {bn::keypad::key_type::B, 736, 1},
    //    {bn::keypad::key_type::R, 741, 1},
    //    {bn::keypad::key_type::B, 744, 1},
    //    {bn::keypad::key_type::B, 752, 1},
    //    {bn::keypad::key_type::A, 752, 1},
    //    {bn::keypad::key_type::B, 760, 1},
    //    {bn::keypad::key_type::R, 765, 1},
    //    {bn::keypad::key_type::B, 768, 1},
    //    {bn::keypad::key_type::B, 776, 1},
    //    {bn::keypad::key_type::RIGHT, 776, 1},
    //    {bn::keypad::key_type::B, 784, 1},
    //    {bn::keypad::key_type::A, 789, 1},
    //    {bn::keypad::key_type::B, 792, 1},
    //    {bn::keypad::key_type::A, 800, 1},
    //    {bn::keypad::key_type::A, 808, 1},
    //    {bn::keypad::key_type::R, 813, 1},
    //    {bn::keypad::key_type::A, 816, 1},
    //    {bn::keypad::key_type::A, 824, 1},
    //    {bn::keypad::key_type::DOWN, 824, 1},
    //    {bn::keypad::key_type::A, 832, 1},
    //    {bn::keypad::key_type::R, 837, 1},
    //    {bn::keypad::key_type::A, 840, 1},
    //    {bn::keypad::key_type::A, 848, 1},
    //    {bn::keypad::key_type::A, 856, 1},
    //    {bn::keypad::key_type::R, 861, 1},
    //    {bn::keypad::key_type::A, 864, 1},
    //    {bn::keypad::key_type::A, 872, 1},
    //    {bn::keypad::key_type::B, 872, 1},
    //    {bn::keypad::key_type::A, 880, 1},
    //    {bn::keypad::key_type::R, 880, 1},
    //    {bn::keypad::key_type::A, 888, 1},
    //    {bn::keypad::key_type::DOWN, 888, 1},
    //    {bn::keypad::key_type::B, 896, 1},
    //    {bn::keypad::key_type::A, 896, 1},
    //    {bn::keypad::key_type::B, 904, 1},
    //    {bn::keypad::key_type::R, 909, 1},
    //    {bn::keypad::key_type::B, 912, 1},
    //    {bn::keypad::key_type::B, 920, 1},
    //    {bn::keypad::key_type::DOWN, 920, 1},
    //    {bn::keypad::key_type::B, 928, 1},
    //    {bn::keypad::key_type::R, 933, 1},
    //    {bn::keypad::key_type::B, 936, 1},
    //    {bn::keypad::key_type::B, 944, 1},
    //    {bn::keypad::key_type::RIGHT, 944, 1},
    //    {bn::keypad::key_type::B, 952, 1},
    //    {bn::keypad::key_type::A, 957, 1},
    //    {bn::keypad::key_type::B, 960, 1},
    //    {bn::keypad::key_type::B, 968, 1},
    //    {bn::keypad::key_type::RIGHT, 968, 1},
    //    {bn::keypad::key_type::B, 976, 1},
    //    {bn::keypad::key_type::A, 981, 1},
    //    {bn::keypad::key_type::B, 984, 1},
    //    {bn::keypad::key_type::DOWN, 992, 1},
    //    {bn::keypad::key_type::L, 992, 1},
    //    {bn::keypad::key_type::DOWN, 1000, 1},
    //    {bn::keypad::key_type::L, 1005, 1},
    //    {bn::keypad::key_type::DOWN, 1008, 1},
    //    {bn::keypad::key_type::DOWN, 1016, 1},
    //    {bn::keypad::key_type::L, 1016, 1},
    //    {bn::keypad::key_type::DOWN, 1024, 1},
    //    {bn::keypad::key_type::L, 1029, 1},
    //    {bn::keypad::key_type::DOWN, 1032, 1},
    //    {bn::keypad::key_type::R, 1040, 1},
    //    {bn::keypad::key_type::L, 1040, 1},
    //    {bn::keypad::key_type::R, 1048, 1},
    //    {bn::keypad::key_type::L, 1053, 1},
    //    {bn::keypad::key_type::R, 1056, 1},
    //    {bn::keypad::key_type::R, 1064, 1},
    //    {bn::keypad::key_type::L, 1064, 1},
    //    {bn::keypad::key_type::R, 1072, 1},
    //    {bn::keypad::key_type::L, 1077, 1},
    //    {bn::keypad::key_type::R, 1080, 1},
    //    {bn::keypad::key_type::B, 1088, 1},
    //    {bn::keypad::key_type::UP, 1088, 1},
    //    {bn::keypad::key_type::B, 1096, 1},
    //    {bn::keypad::key_type::A, 1101, 1},
    //    {bn::keypad::key_type::B, 1104, 1},
    //    {bn::keypad::key_type::B, 1112, 1},
    //    {bn::keypad::key_type::UP, 1112, 1},
    //    {bn::keypad::key_type::B, 1120, 1},
    //    {bn::keypad::key_type::RIGHT, 1125, 1},
    //    {bn::keypad::key_type::B, 1128, 1},
    //    {bn::keypad::key_type::B, 1136, 1},
    //    {bn::keypad::key_type::A, 1136, 1},
    //    {bn::keypad::key_type::A, 1184, 1},
    //    {bn::keypad::key_type::A, 1192, 1},
    //    {bn::keypad::key_type::R, 1197, 1},
    //    {bn::keypad::key_type::A, 1200, 1},
    //    {bn::keypad::key_type::A, 1208, 1},
    //    {bn::keypad::key_type::DOWN, 1208, 1},
    //    {bn::keypad::key_type::A, 1216, 1},
    //    {bn::keypad::key_type::R, 1221, 1},
    //    {bn::keypad::key_type::A, 1224, 1},
    //    {bn::keypad::key_type::A, 1232, 1},
    //    {bn::keypad::key_type::A, 1240, 1},
    //    {bn::keypad::key_type::R, 1245, 1},
    //    {bn::keypad::key_type::A, 1248, 1},
    //    {bn::keypad::key_type::A, 1256, 1},
    //    {bn::keypad::key_type::B, 1256, 1},
    //    {bn::keypad::key_type::A, 1264, 1},
    //    {bn::keypad::key_type::R, 1264, 1},
    //    {bn::keypad::key_type::A, 1272, 1},
    //    {bn::keypad::key_type::DOWN, 1272, 1},
    //    {bn::keypad::key_type::B, 1280, 1},
    //    {bn::keypad::key_type::A, 1280, 1},
    //    {bn::keypad::key_type::B, 1288, 1},
    //    {bn::keypad::key_type::R, 1293, 1},
    //    {bn::keypad::key_type::B, 1296, 1},
    //    {bn::keypad::key_type::B, 1304, 1},
    //    {bn::keypad::key_type::DOWN, 1304, 1},
    //    {bn::keypad::key_type::B, 1312, 1},
    //    {bn::keypad::key_type::R, 1317, 1},
    //    {bn::keypad::key_type::B, 1320, 1},
    //    {bn::keypad::key_type::B, 1328, 1},
    //    {bn::keypad::key_type::A, 1328, 1},
    //    {bn::keypad::key_type::B, 1336, 1},
    //    {bn::keypad::key_type::R, 1341, 1},
    //    {bn::keypad::key_type::B, 1344, 1},
    //    {bn::keypad::key_type::B, 1352, 1},
    //    {bn::keypad::key_type::RIGHT, 1352, 1},
    //    {bn::keypad::key_type::B, 1360, 1},
    //    {bn::keypad::key_type::A, 1365, 1},
    //    {bn::keypad::key_type::B, 1368, 1},
    //    {bn::keypad::key_type::A, 1376, 1},
    //    {bn::keypad::key_type::A, 1384, 1},
    //    {bn::keypad::key_type::R, 1389, 1},
    //    {bn::keypad::key_type::A, 1392, 1},
    //    {bn::keypad::key_type::A, 1400, 1},
    //    {bn::keypad::key_type::DOWN, 1400, 1},
    //    {bn::keypad::key_type::A, 1408, 1},
    //    {bn::keypad::key_type::R, 1413, 1},
    //    {bn::keypad::key_type::A, 1416, 1},
    //    {bn::keypad::key_type::A, 1424, 1},
    //    {bn::keypad::key_type::A, 1432, 1},
    //    {bn::keypad::key_type::R, 1437, 1},
    //    {bn::keypad::key_type::A, 1440, 1},
    //    {bn::keypad::key_type::A, 1448, 1},
    //    {bn::keypad::key_type::B, 1448, 1},
    //    {bn::keypad::key_type::A, 1456, 1},
    //    {bn::keypad::key_type::R, 1456, 1},
    //    {bn::keypad::key_type::A, 1464, 1},
    //    {bn::keypad::key_type::DOWN, 1464, 1},
    //    {bn::keypad::key_type::B, 1472, 1},
    //    {bn::keypad::key_type::A, 1472, 1},
    //    {bn::keypad::key_type::B, 1480, 1},
    //    {bn::keypad::key_type::R, 1485, 1},
    //    {bn::keypad::key_type::B, 1488, 1},
    //    {bn::keypad::key_type::B, 1496, 1},
    //    {bn::keypad::key_type::DOWN, 1496, 1},
    //    {bn::keypad::key_type::B, 1504, 1},
    //    {bn::keypad::key_type::R, 1509, 1},
    //    {bn::keypad::key_type::B, 1512, 1},
    //    {bn::keypad::key_type::B, 1520, 1},
    //    {bn::keypad::key_type::A, 1520, 1},
    //    {bn::keypad::key_type::B, 1528, 1},
    //    {bn::keypad::key_type::R, 1533, 1},
    //    {bn::keypad::key_type::B, 1536, 1},
    //    {bn::keypad::key_type::B, 1544, 1},
    //    {bn::keypad::key_type::RIGHT, 1544, 1},
    //    {bn::keypad::key_type::B, 1552, 1},
    //    {bn::keypad::key_type::A, 1557, 1},
    //    {bn::keypad::key_type::B, 1560, 1}
    //}};
//
    //constexpr bn::array<int, 17> a_new_era_pattern_lengths = {{
    //    32,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96,
    //    96
    //}};
//
    //constexpr song a_new_era = {
    //    a_new_era_data.data(),
    //    a_new_era_data.size(),
    //    a_new_era_pattern_lengths.data(),
    //    236,
    //    "A New Era",
    //    normal,
    //    4,
    //    bn::music_items::e_a_new_era
    //};
    
}

#endif