#ifndef SONG_DATA_H
#define SONG_DATA_H

#include "bn_array.h"
#include "bn_keypad.h"
#include "songs.h"

namespace songs
{
    #ifndef JOAN_OVERRIDE
    constexpr bn::array<note_data, 160> joan_data = {{
        {bn::keypad::key_type::A, 32, 1},
        {bn::keypad::key_type::L, 36, 1},
        {bn::keypad::key_type::RIGHT, 40, 1},
        {bn::keypad::key_type::L, 44, 1},
        {bn::keypad::key_type::A, 48, 1},
        {bn::keypad::key_type::L, 52, 1},
        {bn::keypad::key_type::RIGHT, 56, 1},
        {bn::keypad::key_type::L, 60, 1},
        {bn::keypad::key_type::A, 64, 1},
        {bn::keypad::key_type::L, 68, 1},
        {bn::keypad::key_type::RIGHT, 72, 1},
        {bn::keypad::key_type::L, 76, 1},
        {bn::keypad::key_type::A, 80, 1},
        {bn::keypad::key_type::L, 84, 1},
        {bn::keypad::key_type::RIGHT, 88, 1},
        {bn::keypad::key_type::L, 92, 1},
        {bn::keypad::key_type::A, 96, 1},
        {bn::keypad::key_type::L, 100, 1},
        {bn::keypad::key_type::RIGHT, 104, 1},
        {bn::keypad::key_type::L, 108, 1},
        {bn::keypad::key_type::A, 112, 1},
        {bn::keypad::key_type::L, 116, 1},
        {bn::keypad::key_type::RIGHT, 120, 1},
        {bn::keypad::key_type::L, 124, 1},
        {bn::keypad::key_type::A, 128, 1},
        {bn::keypad::key_type::L, 132, 1},
        {bn::keypad::key_type::RIGHT, 136, 1},
        {bn::keypad::key_type::L, 140, 1},
        {bn::keypad::key_type::A, 144, 1},
        {bn::keypad::key_type::L, 148, 1},
        {bn::keypad::key_type::RIGHT, 152, 1},
        {bn::keypad::key_type::L, 156, 1},
        {bn::keypad::key_type::B, 160, 1},
        {bn::keypad::key_type::L, 164, 1},
        {bn::keypad::key_type::RIGHT, 168, 1},
        {bn::keypad::key_type::L, 172, 1},
        {bn::keypad::key_type::A, 176, 1},
        {bn::keypad::key_type::L, 180, 1},
        {bn::keypad::key_type::RIGHT, 184, 1},
        {bn::keypad::key_type::L, 188, 1},
        {bn::keypad::key_type::B, 192, 1},
        {bn::keypad::key_type::L, 196, 1},
        {bn::keypad::key_type::RIGHT, 200, 1},
        {bn::keypad::key_type::L, 204, 1},
        {bn::keypad::key_type::A, 208, 1},
        {bn::keypad::key_type::L, 212, 1},
        {bn::keypad::key_type::RIGHT, 216, 1},
        {bn::keypad::key_type::L, 220, 1},
        {bn::keypad::key_type::A, 224, 1},
        {bn::keypad::key_type::L, 228, 1},
        {bn::keypad::key_type::RIGHT, 232, 1},
        {bn::keypad::key_type::L, 236, 1},
        {bn::keypad::key_type::A, 240, 1},
        {bn::keypad::key_type::L, 244, 1},
        {bn::keypad::key_type::RIGHT, 248, 1},
        {bn::keypad::key_type::L, 252, 1},
        {bn::keypad::key_type::A, 256, 1},
        {bn::keypad::key_type::L, 260, 1},
        {bn::keypad::key_type::RIGHT, 264, 1},
        {bn::keypad::key_type::L, 268, 1},
        {bn::keypad::key_type::A, 272, 1},
        {bn::keypad::key_type::L, 276, 1},
        {bn::keypad::key_type::RIGHT, 280, 1},
        {bn::keypad::key_type::L, 284, 1},
        {bn::keypad::key_type::B, 288, 1},
        {bn::keypad::key_type::L, 292, 1},
        {bn::keypad::key_type::RIGHT, 296, 1},
        {bn::keypad::key_type::L, 300, 1},
        {bn::keypad::key_type::A, 304, 1},
        {bn::keypad::key_type::L, 308, 1},
        {bn::keypad::key_type::RIGHT, 312, 1},
        {bn::keypad::key_type::L, 316, 1},
        {bn::keypad::key_type::B, 320, 1},
        {bn::keypad::key_type::L, 324, 1},
        {bn::keypad::key_type::RIGHT, 328, 1},
        {bn::keypad::key_type::L, 332, 1},
        {bn::keypad::key_type::A, 336, 1},
        {bn::keypad::key_type::L, 340, 1},
        {bn::keypad::key_type::RIGHT, 344, 1},
        {bn::keypad::key_type::L, 348, 1},
        {bn::keypad::key_type::A, 352, 1},
        {bn::keypad::key_type::A, 356, 1},
        {bn::keypad::key_type::DOWN, 360, 1},
        {bn::keypad::key_type::R, 364, 1},
        {bn::keypad::key_type::DOWN, 368, 1},
        {bn::keypad::key_type::DOWN, 372, 1},
        {bn::keypad::key_type::L, 376, 1},
        {bn::keypad::key_type::R, 380, 1},
        {bn::keypad::key_type::B, 384, 1},
        {bn::keypad::key_type::A, 388, 1},
        {bn::keypad::key_type::L, 392, 1},
        {bn::keypad::key_type::A, 396, 1},
        {bn::keypad::key_type::RIGHT, 400, 1},
        {bn::keypad::key_type::A, 404, 1},
        {bn::keypad::key_type::DOWN, 408, 1},
        {bn::keypad::key_type::R, 412, 1},
        {bn::keypad::key_type::A, 416, 1},
        {bn::keypad::key_type::A, 420, 1},
        {bn::keypad::key_type::DOWN, 424, 1},
        {bn::keypad::key_type::R, 428, 1},
        {bn::keypad::key_type::DOWN, 432, 1},
        {bn::keypad::key_type::DOWN, 436, 1},
        {bn::keypad::key_type::L, 440, 1},
        {bn::keypad::key_type::R, 444, 1},
        {bn::keypad::key_type::B, 448, 1},
        {bn::keypad::key_type::A, 452, 1},
        {bn::keypad::key_type::L, 456, 1},
        {bn::keypad::key_type::A, 460, 1},
        {bn::keypad::key_type::RIGHT, 464, 1},
        {bn::keypad::key_type::A, 468, 1},
        {bn::keypad::key_type::DOWN, 472, 1},
        {bn::keypad::key_type::R, 476, 1},
        {bn::keypad::key_type::A, 480, 1},
        {bn::keypad::key_type::A, 484, 1},
        {bn::keypad::key_type::DOWN, 488, 1},
        {bn::keypad::key_type::R, 492, 1},
        {bn::keypad::key_type::DOWN, 496, 1},
        {bn::keypad::key_type::DOWN, 500, 1},
        {bn::keypad::key_type::L, 504, 1},
        {bn::keypad::key_type::R, 508, 1},
        {bn::keypad::key_type::B, 512, 1},
        {bn::keypad::key_type::A, 516, 1},
        {bn::keypad::key_type::L, 520, 1},
        {bn::keypad::key_type::A, 524, 1},
        {bn::keypad::key_type::RIGHT, 528, 1},
        {bn::keypad::key_type::A, 532, 1},
        {bn::keypad::key_type::DOWN, 536, 1},
        {bn::keypad::key_type::R, 540, 1},
        {bn::keypad::key_type::A, 544, 1},
        {bn::keypad::key_type::A, 548, 1},
        {bn::keypad::key_type::DOWN, 552, 1},
        {bn::keypad::key_type::R, 556, 1},
        {bn::keypad::key_type::DOWN, 560, 1},
        {bn::keypad::key_type::DOWN, 564, 1},
        {bn::keypad::key_type::L, 568, 1},
        {bn::keypad::key_type::R, 572, 1},
        {bn::keypad::key_type::B, 576, 1},
        {bn::keypad::key_type::A, 580, 1},
        {bn::keypad::key_type::L, 584, 1},
        {bn::keypad::key_type::A, 588, 1},
        {bn::keypad::key_type::RIGHT, 592, 1},
        {bn::keypad::key_type::A, 596, 1},
        {bn::keypad::key_type::DOWN, 600, 1},
        {bn::keypad::key_type::R, 604, 1},
        {bn::keypad::key_type::A, 608, 1},
        {bn::keypad::key_type::L, 612, 1},
        {bn::keypad::key_type::RIGHT, 616, 1},
        {bn::keypad::key_type::L, 620, 1},
        {bn::keypad::key_type::A, 624, 1},
        {bn::keypad::key_type::L, 628, 1},
        {bn::keypad::key_type::RIGHT, 632, 1},
        {bn::keypad::key_type::L, 636, 1},
        {bn::keypad::key_type::A, 640, 1},
        {bn::keypad::key_type::L, 644, 1},
        {bn::keypad::key_type::RIGHT, 648, 1},
        {bn::keypad::key_type::L, 652, 1},
        {bn::keypad::key_type::A, 656, 1},
        {bn::keypad::key_type::L, 660, 1},
        {bn::keypad::key_type::RIGHT, 664, 1},
        {bn::keypad::key_type::L, 668, 1}
    }};

    constexpr bn::array<int, 11> joan_pattern_lengths = {{
        32,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64
    }};

    constexpr song joan = {
        joan_data.data(),
        joan_data.size(),
        joan_pattern_lengths.data(),
        120,
        "Joan",
        normal,
        0,
        bn::music_items::a_joan
    };
    #endif

    #ifndef CODENAME_KIDS_NEXT_YEAR_OVERRIDE
    constexpr bn::array<note_data, 601> codename_kids_next_year_data = {{
        {bn::keypad::key_type::RIGHT, 32, 1},
        {bn::keypad::key_type::RIGHT, 36, 1},
        {bn::keypad::key_type::RIGHT, 40, 1},
        {bn::keypad::key_type::RIGHT, 42, 1},
        {bn::keypad::key_type::RIGHT, 44, 1},
        {bn::keypad::key_type::R, 46, 1},
        {bn::keypad::key_type::R, 50, 1},
        {bn::keypad::key_type::R, 52, 1},
        {bn::keypad::key_type::R, 56, 1},
        {bn::keypad::key_type::R, 58, 1},
        {bn::keypad::key_type::R, 60, 1},
        {bn::keypad::key_type::R, 62, 1},
        {bn::keypad::key_type::RIGHT, 64, 1},
        {bn::keypad::key_type::RIGHT, 68, 1},
        {bn::keypad::key_type::RIGHT, 72, 1},
        {bn::keypad::key_type::RIGHT, 74, 1},
        {bn::keypad::key_type::RIGHT, 76, 1},
        {bn::keypad::key_type::R, 78, 1},
        {bn::keypad::key_type::R, 82, 1},
        {bn::keypad::key_type::R, 84, 1},
        {bn::keypad::key_type::R, 88, 1},
        {bn::keypad::key_type::R, 90, 1},
        {bn::keypad::key_type::R, 92, 1},
        {bn::keypad::key_type::R, 94, 1},
        {bn::keypad::key_type::A, 96, 1},
        {bn::keypad::key_type::RIGHT, 160, 1},
        {bn::keypad::key_type::RIGHT, 162, 1},
        {bn::keypad::key_type::RIGHT, 164, 1},
        {bn::keypad::key_type::RIGHT, 166, 1},
        {bn::keypad::key_type::RIGHT, 168, 1},
        {bn::keypad::key_type::RIGHT, 170, 1},
        {bn::keypad::key_type::RIGHT, 172, 1},
        {bn::keypad::key_type::RIGHT, 174, 1},
        {bn::keypad::key_type::R, 176, 1},
        {bn::keypad::key_type::R, 178, 1},
        {bn::keypad::key_type::R, 180, 1},
        {bn::keypad::key_type::R, 182, 1},
        {bn::keypad::key_type::R, 184, 1},
        {bn::keypad::key_type::R, 186, 1},
        {bn::keypad::key_type::R, 188, 1},
        {bn::keypad::key_type::R, 190, 1},
        {bn::keypad::key_type::RIGHT, 192, 1},
        {bn::keypad::key_type::RIGHT, 195, 1},
        {bn::keypad::key_type::RIGHT, 198, 1},
        {bn::keypad::key_type::RIGHT, 200, 1},
        {bn::keypad::key_type::RIGHT, 203, 1},
        {bn::keypad::key_type::RIGHT, 206, 1},
        {bn::keypad::key_type::R, 208, 1},
        {bn::keypad::key_type::R, 211, 1},
        {bn::keypad::key_type::R, 214, 1},
        {bn::keypad::key_type::R, 216, 1},
        {bn::keypad::key_type::R, 219, 1},
        {bn::keypad::key_type::R, 222, 1},
        {bn::keypad::key_type::A, 224, 1},
        {bn::keypad::key_type::A, 272, 1},
        {bn::keypad::key_type::RIGHT, 288, 1},
        {bn::keypad::key_type::RIGHT, 292, 1},
        {bn::keypad::key_type::RIGHT, 296, 1},
        {bn::keypad::key_type::RIGHT, 298, 1},
        {bn::keypad::key_type::RIGHT, 300, 1},
        {bn::keypad::key_type::R, 302, 1},
        {bn::keypad::key_type::R, 306, 1},
        {bn::keypad::key_type::R, 308, 1},
        {bn::keypad::key_type::R, 312, 1},
        {bn::keypad::key_type::R, 314, 1},
        {bn::keypad::key_type::R, 316, 1},
        {bn::keypad::key_type::R, 318, 1},
        {bn::keypad::key_type::RIGHT, 320, 1},
        {bn::keypad::key_type::RIGHT, 324, 1},
        {bn::keypad::key_type::RIGHT, 328, 1},
        {bn::keypad::key_type::RIGHT, 330, 1},
        {bn::keypad::key_type::RIGHT, 332, 1},
        {bn::keypad::key_type::R, 334, 1},
        {bn::keypad::key_type::R, 338, 1},
        {bn::keypad::key_type::R, 340, 1},
        {bn::keypad::key_type::R, 344, 1},
        {bn::keypad::key_type::R, 346, 1},
        {bn::keypad::key_type::R, 348, 1},
        {bn::keypad::key_type::R, 350, 1},
        {bn::keypad::key_type::A, 352, 1},
        {bn::keypad::key_type::A, 356, 1},
        {bn::keypad::key_type::A, 360, 1},
        {bn::keypad::key_type::A, 362, 1},
        {bn::keypad::key_type::A, 364, 1},
        {bn::keypad::key_type::A, 366, 1},
        {bn::keypad::key_type::A, 370, 1},
        {bn::keypad::key_type::A, 372, 1},
        {bn::keypad::key_type::A, 376, 1},
        {bn::keypad::key_type::A, 378, 1},
        {bn::keypad::key_type::A, 380, 1},
        {bn::keypad::key_type::A, 382, 1},
        {bn::keypad::key_type::A, 384, 1},
        {bn::keypad::key_type::A, 388, 1},
        {bn::keypad::key_type::A, 392, 1},
        {bn::keypad::key_type::A, 394, 1},
        {bn::keypad::key_type::A, 396, 1},
        {bn::keypad::key_type::A, 398, 1},
        {bn::keypad::key_type::A, 402, 1},
        {bn::keypad::key_type::A, 404, 1},
        {bn::keypad::key_type::A, 408, 1},
        {bn::keypad::key_type::A, 410, 1},
        {bn::keypad::key_type::A, 412, 1},
        {bn::keypad::key_type::A, 414, 1},
        {bn::keypad::key_type::RIGHT, 416, 1},
        {bn::keypad::key_type::RIGHT, 420, 1},
        {bn::keypad::key_type::RIGHT, 424, 1},
        {bn::keypad::key_type::RIGHT, 426, 1},
        {bn::keypad::key_type::RIGHT, 428, 1},
        {bn::keypad::key_type::R, 430, 1},
        {bn::keypad::key_type::R, 434, 1},
        {bn::keypad::key_type::R, 436, 1},
        {bn::keypad::key_type::R, 440, 1},
        {bn::keypad::key_type::R, 442, 1},
        {bn::keypad::key_type::R, 444, 1},
        {bn::keypad::key_type::R, 446, 1},
        {bn::keypad::key_type::RIGHT, 448, 1},
        {bn::keypad::key_type::RIGHT, 452, 1},
        {bn::keypad::key_type::RIGHT, 456, 1},
        {bn::keypad::key_type::RIGHT, 458, 1},
        {bn::keypad::key_type::RIGHT, 460, 1},
        {bn::keypad::key_type::R, 462, 1},
        {bn::keypad::key_type::R, 466, 1},
        {bn::keypad::key_type::R, 468, 1},
        {bn::keypad::key_type::R, 472, 1},
        {bn::keypad::key_type::R, 474, 1},
        {bn::keypad::key_type::R, 476, 1},
        {bn::keypad::key_type::R, 478, 1},
        {bn::keypad::key_type::A, 480, 1},
        {bn::keypad::key_type::A, 484, 1},
        {bn::keypad::key_type::A, 488, 1},
        {bn::keypad::key_type::A, 490, 1},
        {bn::keypad::key_type::A, 492, 1},
        {bn::keypad::key_type::A, 494, 1},
        {bn::keypad::key_type::A, 498, 1},
        {bn::keypad::key_type::A, 500, 1},
        {bn::keypad::key_type::A, 504, 1},
        {bn::keypad::key_type::A, 506, 1},
        {bn::keypad::key_type::A, 508, 1},
        {bn::keypad::key_type::A, 510, 1},
        {bn::keypad::key_type::A, 512, 1},
        {bn::keypad::key_type::A, 516, 1},
        {bn::keypad::key_type::A, 518, 1},
        {bn::keypad::key_type::A, 520, 1},
        {bn::keypad::key_type::A, 524, 1},
        {bn::keypad::key_type::A, 526, 1},
        {bn::keypad::key_type::A, 528, 1},
        {bn::keypad::key_type::DOWN, 544, 1},
        {bn::keypad::key_type::DOWN, 548, 1},
        {bn::keypad::key_type::DOWN, 552, 1},
        {bn::keypad::key_type::DOWN, 554, 1},
        {bn::keypad::key_type::DOWN, 556, 1},
        {bn::keypad::key_type::DOWN, 558, 1},
        {bn::keypad::key_type::DOWN, 562, 1},
        {bn::keypad::key_type::DOWN, 564, 1},
        {bn::keypad::key_type::DOWN, 568, 1},
        {bn::keypad::key_type::DOWN, 570, 1},
        {bn::keypad::key_type::DOWN, 572, 1},
        {bn::keypad::key_type::DOWN, 574, 1},
        {bn::keypad::key_type::R, 576, 1},
        {bn::keypad::key_type::R, 580, 1},
        {bn::keypad::key_type::R, 584, 1},
        {bn::keypad::key_type::R, 586, 1},
        {bn::keypad::key_type::R, 588, 1},
        {bn::keypad::key_type::R, 590, 1},
        {bn::keypad::key_type::R, 594, 1},
        {bn::keypad::key_type::R, 596, 1},
        {bn::keypad::key_type::R, 600, 1},
        {bn::keypad::key_type::R, 602, 1},
        {bn::keypad::key_type::R, 604, 1},
        {bn::keypad::key_type::R, 606, 1},
        {bn::keypad::key_type::B, 608, 1},
        {bn::keypad::key_type::B, 612, 1},
        {bn::keypad::key_type::L, 616, 1},
        {bn::keypad::key_type::UP, 618, 1},
        {bn::keypad::key_type::A, 624, 1},
        {bn::keypad::key_type::A, 626, 1},
        {bn::keypad::key_type::A, 628, 1},
        {bn::keypad::key_type::A, 630, 1},
        {bn::keypad::key_type::RIGHT, 632, 1},
        {bn::keypad::key_type::RIGHT, 634, 1},
        {bn::keypad::key_type::RIGHT, 636, 1},
        {bn::keypad::key_type::RIGHT, 638, 1},
        {bn::keypad::key_type::B, 640, 1},
        {bn::keypad::key_type::B, 644, 1},
        {bn::keypad::key_type::L, 648, 1},
        {bn::keypad::key_type::UP, 650, 1},
        {bn::keypad::key_type::A, 656, 1},
        {bn::keypad::key_type::A, 658, 1},
        {bn::keypad::key_type::A, 660, 1},
        {bn::keypad::key_type::A, 662, 1},
        {bn::keypad::key_type::RIGHT, 664, 1},
        {bn::keypad::key_type::RIGHT, 666, 1},
        {bn::keypad::key_type::RIGHT, 668, 1},
        {bn::keypad::key_type::RIGHT, 670, 1},
        {bn::keypad::key_type::DOWN, 672, 1},
        {bn::keypad::key_type::DOWN, 676, 1},
        {bn::keypad::key_type::DOWN, 680, 1},
        {bn::keypad::key_type::DOWN, 682, 1},
        {bn::keypad::key_type::DOWN, 684, 1},
        {bn::keypad::key_type::DOWN, 686, 1},
        {bn::keypad::key_type::DOWN, 690, 1},
        {bn::keypad::key_type::DOWN, 692, 1},
        {bn::keypad::key_type::DOWN, 696, 1},
        {bn::keypad::key_type::DOWN, 698, 1},
        {bn::keypad::key_type::DOWN, 700, 1},
        {bn::keypad::key_type::DOWN, 702, 1},
        {bn::keypad::key_type::R, 704, 1},
        {bn::keypad::key_type::R, 708, 1},
        {bn::keypad::key_type::R, 712, 1},
        {bn::keypad::key_type::R, 714, 1},
        {bn::keypad::key_type::R, 716, 1},
        {bn::keypad::key_type::R, 718, 1},
        {bn::keypad::key_type::R, 722, 1},
        {bn::keypad::key_type::R, 724, 1},
        {bn::keypad::key_type::R, 728, 1},
        {bn::keypad::key_type::R, 730, 1},
        {bn::keypad::key_type::R, 732, 1},
        {bn::keypad::key_type::R, 734, 1},
        {bn::keypad::key_type::B, 736, 1},
        {bn::keypad::key_type::B, 740, 1},
        {bn::keypad::key_type::L, 744, 1},
        {bn::keypad::key_type::UP, 746, 1},
        {bn::keypad::key_type::A, 752, 1},
        {bn::keypad::key_type::A, 754, 1},
        {bn::keypad::key_type::A, 756, 1},
        {bn::keypad::key_type::A, 758, 1},
        {bn::keypad::key_type::RIGHT, 760, 1},
        {bn::keypad::key_type::RIGHT, 762, 1},
        {bn::keypad::key_type::RIGHT, 764, 1},
        {bn::keypad::key_type::RIGHT, 766, 1},
        {bn::keypad::key_type::B, 768, 1},
        {bn::keypad::key_type::B, 772, 1},
        {bn::keypad::key_type::L, 776, 1},
        {bn::keypad::key_type::UP, 778, 1},
        {bn::keypad::key_type::A, 784, 1},
        {bn::keypad::key_type::A, 786, 1},
        {bn::keypad::key_type::A, 788, 1},
        {bn::keypad::key_type::A, 790, 1},
        {bn::keypad::key_type::RIGHT, 792, 1},
        {bn::keypad::key_type::RIGHT, 794, 1},
        {bn::keypad::key_type::RIGHT, 796, 1},
        {bn::keypad::key_type::RIGHT, 798, 1},
        {bn::keypad::key_type::A, 800, 1},
        {bn::keypad::key_type::A, 804, 1},
        {bn::keypad::key_type::A, 808, 1},
        {bn::keypad::key_type::A, 810, 1},
        {bn::keypad::key_type::A, 812, 1},
        {bn::keypad::key_type::A, 814, 1},
        {bn::keypad::key_type::A, 818, 1},
        {bn::keypad::key_type::A, 820, 1},
        {bn::keypad::key_type::A, 824, 1},
        {bn::keypad::key_type::A, 826, 1},
        {bn::keypad::key_type::A, 828, 1},
        {bn::keypad::key_type::A, 830, 1},
        {bn::keypad::key_type::DOWN, 832, 1},
        {bn::keypad::key_type::DOWN, 836, 1},
        {bn::keypad::key_type::DOWN, 840, 1},
        {bn::keypad::key_type::DOWN, 842, 1},
        {bn::keypad::key_type::DOWN, 844, 1},
        {bn::keypad::key_type::DOWN, 846, 1},
        {bn::keypad::key_type::DOWN, 850, 1},
        {bn::keypad::key_type::DOWN, 852, 1},
        {bn::keypad::key_type::DOWN, 856, 1},
        {bn::keypad::key_type::DOWN, 858, 1},
        {bn::keypad::key_type::DOWN, 860, 1},
        {bn::keypad::key_type::DOWN, 862, 1},
        {bn::keypad::key_type::R, 864, 1},
        {bn::keypad::key_type::R, 866, 1},
        {bn::keypad::key_type::DOWN, 870, 1},
        {bn::keypad::key_type::DOWN, 872, 1},
        {bn::keypad::key_type::A, 876, 1},
        {bn::keypad::key_type::A, 878, 1},
        {bn::keypad::key_type::A, 882, 1},
        {bn::keypad::key_type::A, 884, 1},
        {bn::keypad::key_type::A, 888, 1},
        {bn::keypad::key_type::A, 890, 1},
        {bn::keypad::key_type::A, 892, 1},
        {bn::keypad::key_type::A, 894, 1},
        {bn::keypad::key_type::R, 896, 1},
        {bn::keypad::key_type::R, 898, 1},
        {bn::keypad::key_type::DOWN, 902, 1},
        {bn::keypad::key_type::DOWN, 904, 1},
        {bn::keypad::key_type::A, 908, 1},
        {bn::keypad::key_type::A, 910, 1},
        {bn::keypad::key_type::A, 914, 1},
        {bn::keypad::key_type::A, 916, 1},
        {bn::keypad::key_type::A, 920, 1},
        {bn::keypad::key_type::A, 922, 1},
        {bn::keypad::key_type::A, 924, 1},
        {bn::keypad::key_type::A, 926, 1},
        {bn::keypad::key_type::A, 928, 1},
        {bn::keypad::key_type::A, 932, 1},
        {bn::keypad::key_type::A, 936, 1},
        {bn::keypad::key_type::A, 938, 1},
        {bn::keypad::key_type::A, 940, 1},
        {bn::keypad::key_type::A, 942, 1},
        {bn::keypad::key_type::A, 946, 1},
        {bn::keypad::key_type::A, 948, 1},
        {bn::keypad::key_type::A, 952, 1},
        {bn::keypad::key_type::A, 954, 1},
        {bn::keypad::key_type::A, 956, 1},
        {bn::keypad::key_type::A, 958, 1},
        {bn::keypad::key_type::DOWN, 960, 1},
        {bn::keypad::key_type::DOWN, 964, 1},
        {bn::keypad::key_type::DOWN, 968, 1},
        {bn::keypad::key_type::DOWN, 970, 1},
        {bn::keypad::key_type::DOWN, 972, 1},
        {bn::keypad::key_type::DOWN, 974, 1},
        {bn::keypad::key_type::DOWN, 978, 1},
        {bn::keypad::key_type::DOWN, 980, 1},
        {bn::keypad::key_type::DOWN, 984, 1},
        {bn::keypad::key_type::DOWN, 986, 1},
        {bn::keypad::key_type::DOWN, 988, 1},
        {bn::keypad::key_type::DOWN, 990, 1},
        {bn::keypad::key_type::R, 992, 1},
        {bn::keypad::key_type::R, 994, 1},
        {bn::keypad::key_type::DOWN, 998, 1},
        {bn::keypad::key_type::DOWN, 1000, 1},
        {bn::keypad::key_type::A, 1004, 1},
        {bn::keypad::key_type::A, 1006, 1},
        {bn::keypad::key_type::A, 1010, 1},
        {bn::keypad::key_type::A, 1012, 1},
        {bn::keypad::key_type::A, 1016, 1},
        {bn::keypad::key_type::A, 1018, 1},
        {bn::keypad::key_type::A, 1020, 1},
        {bn::keypad::key_type::A, 1022, 1},
        {bn::keypad::key_type::R, 1024, 1},
        {bn::keypad::key_type::R, 1026, 1},
        {bn::keypad::key_type::DOWN, 1030, 1},
        {bn::keypad::key_type::DOWN, 1032, 1},
        {bn::keypad::key_type::A, 1036, 1},
        {bn::keypad::key_type::A, 1038, 1},
        {bn::keypad::key_type::A, 1042, 1},
        {bn::keypad::key_type::A, 1044, 1},
        {bn::keypad::key_type::A, 1048, 1},
        {bn::keypad::key_type::A, 1050, 1},
        {bn::keypad::key_type::A, 1052, 1},
        {bn::keypad::key_type::A, 1054, 1},
        {bn::keypad::key_type::R, 1056, 1},
        {bn::keypad::key_type::R, 1058, 1},
        {bn::keypad::key_type::DOWN, 1062, 1},
        {bn::keypad::key_type::DOWN, 1064, 1},
        {bn::keypad::key_type::A, 1068, 1},
        {bn::keypad::key_type::A, 1070, 1},
        {bn::keypad::key_type::A, 1074, 1},
        {bn::keypad::key_type::A, 1076, 1},
        {bn::keypad::key_type::A, 1080, 1},
        {bn::keypad::key_type::A, 1082, 1},
        {bn::keypad::key_type::A, 1084, 1},
        {bn::keypad::key_type::A, 1086, 1},
        {bn::keypad::key_type::R, 1088, 1},
        {bn::keypad::key_type::R, 1090, 1},
        {bn::keypad::key_type::DOWN, 1094, 1},
        {bn::keypad::key_type::DOWN, 1096, 1},
        {bn::keypad::key_type::A, 1100, 1},
        {bn::keypad::key_type::A, 1102, 1},
        {bn::keypad::key_type::A, 1106, 1},
        {bn::keypad::key_type::A, 1108, 1},
        {bn::keypad::key_type::A, 1112, 1},
        {bn::keypad::key_type::A, 1114, 1},
        {bn::keypad::key_type::A, 1116, 1},
        {bn::keypad::key_type::A, 1118, 1},
        {bn::keypad::key_type::R, 1120, 1},
        {bn::keypad::key_type::R, 1124, 1},
        {bn::keypad::key_type::R, 1130, 1},
        {bn::keypad::key_type::R, 1134, 1},
        {bn::keypad::key_type::R, 1138, 1},
        {bn::keypad::key_type::R, 1140, 1},
        {bn::keypad::key_type::R, 1144, 1},
        {bn::keypad::key_type::R, 1146, 1},
        {bn::keypad::key_type::R, 1148, 1},
        {bn::keypad::key_type::R, 1150, 1},
        {bn::keypad::key_type::RIGHT, 1152, 1},
        {bn::keypad::key_type::RIGHT, 1156, 1},
        {bn::keypad::key_type::RIGHT, 1162, 1},
        {bn::keypad::key_type::RIGHT, 1166, 1},
        {bn::keypad::key_type::RIGHT, 1170, 1},
        {bn::keypad::key_type::RIGHT, 1172, 1},
        {bn::keypad::key_type::RIGHT, 1174, 1},
        {bn::keypad::key_type::RIGHT, 1176, 1},
        {bn::keypad::key_type::RIGHT, 1178, 1},
        {bn::keypad::key_type::RIGHT, 1180, 1},
        {bn::keypad::key_type::RIGHT, 1182, 1},
        {bn::keypad::key_type::R, 1184, 1},
        {bn::keypad::key_type::R, 1188, 1},
        {bn::keypad::key_type::R, 1194, 1},
        {bn::keypad::key_type::R, 1198, 1},
        {bn::keypad::key_type::R, 1202, 1},
        {bn::keypad::key_type::R, 1204, 1},
        {bn::keypad::key_type::R, 1208, 1},
        {bn::keypad::key_type::R, 1210, 1},
        {bn::keypad::key_type::R, 1212, 1},
        {bn::keypad::key_type::R, 1214, 1},
        {bn::keypad::key_type::RIGHT, 1216, 1},
        {bn::keypad::key_type::RIGHT, 1220, 1},
        {bn::keypad::key_type::RIGHT, 1226, 1},
        {bn::keypad::key_type::RIGHT, 1230, 1},
        {bn::keypad::key_type::RIGHT, 1234, 1},
        {bn::keypad::key_type::RIGHT, 1236, 1},
        {bn::keypad::key_type::RIGHT, 1238, 1},
        {bn::keypad::key_type::RIGHT, 1240, 1},
        {bn::keypad::key_type::RIGHT, 1242, 1},
        {bn::keypad::key_type::RIGHT, 1244, 1},
        {bn::keypad::key_type::RIGHT, 1246, 1},
        {bn::keypad::key_type::R, 1248, 1},
        {bn::keypad::key_type::R, 1252, 1},
        {bn::keypad::key_type::R, 1258, 1},
        {bn::keypad::key_type::R, 1262, 1},
        {bn::keypad::key_type::R, 1266, 1},
        {bn::keypad::key_type::R, 1268, 1},
        {bn::keypad::key_type::R, 1272, 1},
        {bn::keypad::key_type::R, 1274, 1},
        {bn::keypad::key_type::R, 1276, 1},
        {bn::keypad::key_type::R, 1278, 1},
        {bn::keypad::key_type::RIGHT, 1280, 1},
        {bn::keypad::key_type::RIGHT, 1284, 1},
        {bn::keypad::key_type::RIGHT, 1290, 1},
        {bn::keypad::key_type::RIGHT, 1294, 1},
        {bn::keypad::key_type::RIGHT, 1298, 1},
        {bn::keypad::key_type::RIGHT, 1300, 1},
        {bn::keypad::key_type::RIGHT, 1302, 1},
        {bn::keypad::key_type::RIGHT, 1304, 1},
        {bn::keypad::key_type::RIGHT, 1306, 1},
        {bn::keypad::key_type::RIGHT, 1308, 1},
        {bn::keypad::key_type::RIGHT, 1310, 1},
        {bn::keypad::key_type::DOWN, 1312, 1},
        {bn::keypad::key_type::DOWN, 1316, 1},
        {bn::keypad::key_type::DOWN, 1322, 1},
        {bn::keypad::key_type::DOWN, 1326, 1},
        {bn::keypad::key_type::DOWN, 1330, 1},
        {bn::keypad::key_type::DOWN, 1332, 1},
        {bn::keypad::key_type::DOWN, 1336, 1},
        {bn::keypad::key_type::DOWN, 1338, 1},
        {bn::keypad::key_type::DOWN, 1340, 1},
        {bn::keypad::key_type::DOWN, 1342, 1},
        {bn::keypad::key_type::DOWN, 1344, 1},
        {bn::keypad::key_type::DOWN, 1346, 1},
        {bn::keypad::key_type::DOWN, 1350, 1},
        {bn::keypad::key_type::DOWN, 1352, 1},
        {bn::keypad::key_type::DOWN, 1354, 1},
        {bn::keypad::key_type::DOWN, 1358, 1},
        {bn::keypad::key_type::DOWN, 1360, 1},
        {bn::keypad::key_type::DOWN, 1362, 1},
        {bn::keypad::key_type::DOWN, 1366, 1},
        {bn::keypad::key_type::DOWN, 1368, 1},
        {bn::keypad::key_type::DOWN, 1370, 1},
        {bn::keypad::key_type::DOWN, 1372, 1},
        {bn::keypad::key_type::DOWN, 1374, 1},
        {bn::keypad::key_type::B, 1376, 1},
        {bn::keypad::key_type::B, 1380, 1},
        {bn::keypad::key_type::L, 1384, 1},
        {bn::keypad::key_type::UP, 1386, 1},
        {bn::keypad::key_type::A, 1392, 1},
        {bn::keypad::key_type::A, 1394, 1},
        {bn::keypad::key_type::A, 1396, 1},
        {bn::keypad::key_type::A, 1398, 1},
        {bn::keypad::key_type::RIGHT, 1400, 1},
        {bn::keypad::key_type::RIGHT, 1402, 1},
        {bn::keypad::key_type::RIGHT, 1404, 1},
        {bn::keypad::key_type::RIGHT, 1406, 1},
        {bn::keypad::key_type::B, 1408, 1},
        {bn::keypad::key_type::B, 1412, 1},
        {bn::keypad::key_type::L, 1416, 1},
        {bn::keypad::key_type::UP, 1418, 1},
        {bn::keypad::key_type::A, 1424, 1},
        {bn::keypad::key_type::A, 1427, 1},
        {bn::keypad::key_type::A, 1430, 1},
        {bn::keypad::key_type::RIGHT, 1432, 1},
        {bn::keypad::key_type::RIGHT, 1435, 1},
        {bn::keypad::key_type::RIGHT, 1438, 1},
        {bn::keypad::key_type::B, 1440, 1},
        {bn::keypad::key_type::B, 1444, 1},
        {bn::keypad::key_type::L, 1448, 1},
        {bn::keypad::key_type::UP, 1450, 1},
        {bn::keypad::key_type::A, 1456, 1},
        {bn::keypad::key_type::A, 1458, 1},
        {bn::keypad::key_type::A, 1460, 1},
        {bn::keypad::key_type::A, 1462, 1},
        {bn::keypad::key_type::RIGHT, 1464, 1},
        {bn::keypad::key_type::RIGHT, 1466, 1},
        {bn::keypad::key_type::RIGHT, 1468, 1},
        {bn::keypad::key_type::RIGHT, 1470, 1},
        {bn::keypad::key_type::B, 1472, 1},
        {bn::keypad::key_type::B, 1476, 1},
        {bn::keypad::key_type::L, 1480, 1},
        {bn::keypad::key_type::UP, 1482, 1},
        {bn::keypad::key_type::A, 1488, 1},
        {bn::keypad::key_type::A, 1491, 1},
        {bn::keypad::key_type::A, 1494, 1},
        {bn::keypad::key_type::RIGHT, 1496, 1},
        {bn::keypad::key_type::DOWN, 1520, 1},
        {bn::keypad::key_type::R, 1552, 1},
        {bn::keypad::key_type::L, 1554, 1},
        {bn::keypad::key_type::B, 1584, 1},
        {bn::keypad::key_type::L, 1588, 1},
        {bn::keypad::key_type::RIGHT, 1593, 1},
        {bn::keypad::key_type::L, 1598, 1},
        {bn::keypad::key_type::A, 1603, 1},
        {bn::keypad::key_type::L, 1608, 1},
        {bn::keypad::key_type::RIGHT, 1613, 1},
        {bn::keypad::key_type::L, 1618, 1},
        {bn::keypad::key_type::B, 1623, 1},
        {bn::keypad::key_type::L, 1629, 1},
        {bn::keypad::key_type::RIGHT, 1635, 1},
        {bn::keypad::key_type::L, 1642, 1},
        {bn::keypad::key_type::A, 1650, 1},
        {bn::keypad::key_type::DOWN, 1696, 1},
        {bn::keypad::key_type::DOWN, 1700, 1},
        {bn::keypad::key_type::DOWN, 1704, 1},
        {bn::keypad::key_type::DOWN, 1708, 1},
        {bn::keypad::key_type::DOWN, 1712, 1},
        {bn::keypad::key_type::DOWN, 1716, 1},
        {bn::keypad::key_type::DOWN, 1720, 1},
        {bn::keypad::key_type::DOWN, 1724, 1},
        {bn::keypad::key_type::R, 1728, 1},
        {bn::keypad::key_type::R, 1732, 1},
        {bn::keypad::key_type::R, 1736, 1},
        {bn::keypad::key_type::R, 1740, 1},
        {bn::keypad::key_type::R, 1744, 1},
        {bn::keypad::key_type::R, 1748, 1},
        {bn::keypad::key_type::R, 1752, 1},
        {bn::keypad::key_type::R, 1756, 1},
        {bn::keypad::key_type::B, 1760, 1},
        {bn::keypad::key_type::B, 1764, 1},
        {bn::keypad::key_type::L, 1768, 1},
        {bn::keypad::key_type::UP, 1770, 1},
        {bn::keypad::key_type::A, 1776, 1},
        {bn::keypad::key_type::A, 1778, 1},
        {bn::keypad::key_type::A, 1780, 1},
        {bn::keypad::key_type::A, 1782, 1},
        {bn::keypad::key_type::RIGHT, 1784, 1},
        {bn::keypad::key_type::RIGHT, 1786, 1},
        {bn::keypad::key_type::RIGHT, 1788, 1},
        {bn::keypad::key_type::RIGHT, 1790, 1},
        {bn::keypad::key_type::B, 1792, 1},
        {bn::keypad::key_type::B, 1796, 1},
        {bn::keypad::key_type::L, 1800, 1},
        {bn::keypad::key_type::UP, 1802, 1},
        {bn::keypad::key_type::A, 1808, 1},
        {bn::keypad::key_type::A, 1810, 1},
        {bn::keypad::key_type::A, 1812, 1},
        {bn::keypad::key_type::A, 1814, 1},
        {bn::keypad::key_type::RIGHT, 1816, 1},
        {bn::keypad::key_type::RIGHT, 1818, 1},
        {bn::keypad::key_type::RIGHT, 1820, 1},
        {bn::keypad::key_type::RIGHT, 1822, 1},
        {bn::keypad::key_type::DOWN, 1824, 1},
        {bn::keypad::key_type::DOWN, 1828, 1},
        {bn::keypad::key_type::DOWN, 1832, 1},
        {bn::keypad::key_type::DOWN, 1836, 1},
        {bn::keypad::key_type::DOWN, 1840, 1},
        {bn::keypad::key_type::DOWN, 1844, 1},
        {bn::keypad::key_type::DOWN, 1848, 1},
        {bn::keypad::key_type::DOWN, 1852, 1},
        {bn::keypad::key_type::R, 1856, 1},
        {bn::keypad::key_type::R, 1860, 1},
        {bn::keypad::key_type::R, 1864, 1},
        {bn::keypad::key_type::R, 1868, 1},
        {bn::keypad::key_type::R, 1872, 1},
        {bn::keypad::key_type::R, 1876, 1},
        {bn::keypad::key_type::R, 1880, 1},
        {bn::keypad::key_type::R, 1884, 1},
        {bn::keypad::key_type::B, 1888, 1},
        {bn::keypad::key_type::B, 1892, 1},
        {bn::keypad::key_type::L, 1896, 1},
        {bn::keypad::key_type::UP, 1898, 1},
        {bn::keypad::key_type::A, 1904, 1},
        {bn::keypad::key_type::A, 1906, 1},
        {bn::keypad::key_type::A, 1908, 1},
        {bn::keypad::key_type::A, 1910, 1},
        {bn::keypad::key_type::RIGHT, 1912, 1},
        {bn::keypad::key_type::RIGHT, 1914, 1},
        {bn::keypad::key_type::RIGHT, 1916, 1},
        {bn::keypad::key_type::RIGHT, 1918, 1},
        {bn::keypad::key_type::B, 1920, 1},
        {bn::keypad::key_type::B, 1924, 1},
        {bn::keypad::key_type::L, 1928, 1},
        {bn::keypad::key_type::UP, 1930, 1},
        {bn::keypad::key_type::A, 1936, 1},
        {bn::keypad::key_type::A, 1939, 1},
        {bn::keypad::key_type::A, 1942, 1},
        {bn::keypad::key_type::A, 1944, 1},
        {bn::keypad::key_type::A, 1947, 1},
        {bn::keypad::key_type::A, 1950, 1},
        {bn::keypad::key_type::DOWN, 1952, 1},
        {bn::keypad::key_type::DOWN, 1956, 1},
        {bn::keypad::key_type::DOWN, 1960, 1},
        {bn::keypad::key_type::DOWN, 1964, 1},
        {bn::keypad::key_type::DOWN, 1968, 1},
        {bn::keypad::key_type::DOWN, 1972, 1},
        {bn::keypad::key_type::DOWN, 1976, 1},
        {bn::keypad::key_type::DOWN, 1980, 1},
        {bn::keypad::key_type::DOWN, 1982, 1},
        {bn::keypad::key_type::R, 1984, 1},
        {bn::keypad::key_type::R, 1988, 1},
        {bn::keypad::key_type::R, 1992, 1},
        {bn::keypad::key_type::R, 1996, 1},
        {bn::keypad::key_type::A, 2000, 1},
        {bn::keypad::key_type::A, 2003, 1},
        {bn::keypad::key_type::A, 2006, 1},
        {bn::keypad::key_type::A, 2008, 1}
    }};

    constexpr bn::array<int, 32> codename_kids_next_year_pattern_lengths = {{
        32,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64,
        64
    }};

    constexpr song codename_kids_next_year = {
        codename_kids_next_year_data.data(),
        codename_kids_next_year_data.size(),
        codename_kids_next_year_pattern_lengths.data(),
        180,
        "Codename Kids Next Year",
        normal,
        1,
        bn::music_items::b_codename_kids_next_year
    };
    #endif

    constexpr bn::array<const song*, 2> all_songs = {{
        &joan,
        &codename_kids_next_year
    }};
}
#endif