#ifndef SONG_DATA_H
#define SONG_DATA_H

#include "bn_array.h"
#include "bn_keypad.h"
#include "songs.h"

namespace songs
{
    #ifndef FASTEST_KID_ALIVE_OVERRIDE
    constexpr bn::array<note_data, 77> fastest_kid_alive_data = {{
        {bn::keypad::key_type::R, 30, 1},
        {bn::keypad::key_type::R, 36, 1},
        {bn::keypad::key_type::R, 42, 1},
        {bn::keypad::key_type::DOWN, 46, 1},
        {bn::keypad::key_type::DOWN, 50, 1},
        {bn::keypad::key_type::DOWN, 54, 1},
        {bn::keypad::key_type::DOWN, 58, 1},
        {bn::keypad::key_type::DOWN, 60, 1},
        {bn::keypad::key_type::DOWN, 62, 1},
        {bn::keypad::key_type::B, 64, 1},
        {bn::keypad::key_type::B, 68, 1},
        {bn::keypad::key_type::B, 74, 1},
        {bn::keypad::key_type::UP, 78, 1},
        {bn::keypad::key_type::RIGHT, 82, 1},
        {bn::keypad::key_type::A, 86, 1},
        {bn::keypad::key_type::DOWN, 90, 1},
        {bn::keypad::key_type::R, 94, 1},
        {bn::keypad::key_type::R, 100, 1},
        {bn::keypad::key_type::R, 106, 1},
        {bn::keypad::key_type::RIGHT, 110, 1},
        {bn::keypad::key_type::RIGHT, 114, 1},
        {bn::keypad::key_type::RIGHT, 118, 1},
        {bn::keypad::key_type::RIGHT, 122, 1},
        {bn::keypad::key_type::RIGHT, 124, 1},
        {bn::keypad::key_type::RIGHT, 126, 1},
        {bn::keypad::key_type::UP, 128, 1},
        {bn::keypad::key_type::UP, 130, 1},
        {bn::keypad::key_type::UP, 134, 1},
        {bn::keypad::key_type::UP, 136, 1},
        {bn::keypad::key_type::UP, 138, 1},
        {bn::keypad::key_type::UP, 142, 1},
        {bn::keypad::key_type::UP, 144, 1},
        {bn::keypad::key_type::UP, 146, 1},
        {bn::keypad::key_type::UP, 150, 1},
        {bn::keypad::key_type::UP, 152, 1},
        {bn::keypad::key_type::UP, 154, 1},
        {bn::keypad::key_type::UP, 156, 1},
        {bn::keypad::key_type::UP, 158, 1},
        {bn::keypad::key_type::R, 160, 1},
        {bn::keypad::key_type::R, 164, 1},
        {bn::keypad::key_type::R, 170, 1},
        {bn::keypad::key_type::DOWN, 174, 1},
        {bn::keypad::key_type::DOWN, 178, 1},
        {bn::keypad::key_type::DOWN, 182, 1},
        {bn::keypad::key_type::DOWN, 184, 1},
        {bn::keypad::key_type::R, 185, 1},
        {bn::keypad::key_type::DOWN, 186, 1},
        {bn::keypad::key_type::DOWN, 188, 1},
        {bn::keypad::key_type::B, 192, 1},
        {bn::keypad::key_type::B, 196, 1},
        {bn::keypad::key_type::B, 202, 1},
        {bn::keypad::key_type::UP, 206, 1},
        {bn::keypad::key_type::RIGHT, 210, 1},
        {bn::keypad::key_type::A, 214, 1},
        {bn::keypad::key_type::DOWN, 218, 1},
        {bn::keypad::key_type::R, 222, 1},
        {bn::keypad::key_type::R, 228, 1},
        {bn::keypad::key_type::R, 234, 1},
        {bn::keypad::key_type::RIGHT, 238, 1},
        {bn::keypad::key_type::RIGHT, 242, 1},
        {bn::keypad::key_type::RIGHT, 246, 1},
        {bn::keypad::key_type::RIGHT, 250, 1},
        {bn::keypad::key_type::RIGHT, 252, 1},
        {bn::keypad::key_type::RIGHT, 254, 1},
        {bn::keypad::key_type::UP, 256, 1},
        {bn::keypad::key_type::UP, 258, 1},
        {bn::keypad::key_type::UP, 262, 1},
        {bn::keypad::key_type::UP, 264, 1},
        {bn::keypad::key_type::UP, 266, 1},
        {bn::keypad::key_type::UP, 270, 1},
        {bn::keypad::key_type::UP, 272, 1},
        {bn::keypad::key_type::UP, 274, 1},
        {bn::keypad::key_type::UP, 278, 1},
        {bn::keypad::key_type::UP, 280, 1},
        {bn::keypad::key_type::UP, 282, 1},
        {bn::keypad::key_type::UP, 284, 1},
        {bn::keypad::key_type::UP, 286, 1}
    }};

    constexpr song fastest_kid_alive = {
        fastest_kid_alive_data.data(),
        fastest_kid_alive_data.size(),
        180,
        "Fastest Kid Alive",
        normal,
        0,
        bn::music_items::a_fastest_kid_alive
    };
    #endif

    #ifndef JOAN_OVERRIDE
    constexpr bn::array<note_data, 160> joan_data = {{
        {bn::keypad::key_type::A, 32, 1},
        {bn::keypad::key_type::L, 36, 1},
        {bn::keypad::key_type::RIGHT, 40, 1},
        {bn::keypad::key_type::L, 44, 1},
        {bn::keypad::key_type::A, 48, 1},
        {bn::keypad::key_type::L, 52, 1},
        {bn::keypad::key_type::RIGHT, 56, 1},
        {bn::keypad::key_type::L, 60, 1},
        {bn::keypad::key_type::A, 64, 1},
        {bn::keypad::key_type::L, 68, 1},
        {bn::keypad::key_type::RIGHT, 72, 1},
        {bn::keypad::key_type::L, 76, 1},
        {bn::keypad::key_type::A, 80, 1},
        {bn::keypad::key_type::L, 84, 1},
        {bn::keypad::key_type::RIGHT, 88, 1},
        {bn::keypad::key_type::L, 92, 1},
        {bn::keypad::key_type::A, 96, 1},
        {bn::keypad::key_type::L, 100, 1},
        {bn::keypad::key_type::RIGHT, 104, 1},
        {bn::keypad::key_type::L, 108, 1},
        {bn::keypad::key_type::A, 112, 1},
        {bn::keypad::key_type::L, 116, 1},
        {bn::keypad::key_type::RIGHT, 120, 1},
        {bn::keypad::key_type::L, 124, 1},
        {bn::keypad::key_type::A, 128, 1},
        {bn::keypad::key_type::L, 132, 1},
        {bn::keypad::key_type::RIGHT, 136, 1},
        {bn::keypad::key_type::L, 140, 1},
        {bn::keypad::key_type::A, 144, 1},
        {bn::keypad::key_type::L, 148, 1},
        {bn::keypad::key_type::RIGHT, 152, 1},
        {bn::keypad::key_type::L, 156, 1},
        {bn::keypad::key_type::B, 160, 1},
        {bn::keypad::key_type::L, 164, 1},
        {bn::keypad::key_type::RIGHT, 168, 1},
        {bn::keypad::key_type::L, 172, 1},
        {bn::keypad::key_type::A, 176, 1},
        {bn::keypad::key_type::L, 180, 1},
        {bn::keypad::key_type::RIGHT, 184, 1},
        {bn::keypad::key_type::L, 188, 1},
        {bn::keypad::key_type::B, 192, 1},
        {bn::keypad::key_type::L, 196, 1},
        {bn::keypad::key_type::RIGHT, 200, 1},
        {bn::keypad::key_type::L, 204, 1},
        {bn::keypad::key_type::A, 208, 1},
        {bn::keypad::key_type::L, 212, 1},
        {bn::keypad::key_type::RIGHT, 216, 1},
        {bn::keypad::key_type::L, 220, 1},
        {bn::keypad::key_type::A, 224, 1},
        {bn::keypad::key_type::L, 228, 1},
        {bn::keypad::key_type::RIGHT, 232, 1},
        {bn::keypad::key_type::L, 236, 1},
        {bn::keypad::key_type::A, 240, 1},
        {bn::keypad::key_type::L, 244, 1},
        {bn::keypad::key_type::RIGHT, 248, 1},
        {bn::keypad::key_type::L, 252, 1},
        {bn::keypad::key_type::A, 256, 1},
        {bn::keypad::key_type::L, 260, 1},
        {bn::keypad::key_type::RIGHT, 264, 1},
        {bn::keypad::key_type::L, 268, 1},
        {bn::keypad::key_type::A, 272, 1},
        {bn::keypad::key_type::L, 276, 1},
        {bn::keypad::key_type::RIGHT, 280, 1},
        {bn::keypad::key_type::L, 284, 1},
        {bn::keypad::key_type::B, 288, 1},
        {bn::keypad::key_type::L, 292, 1},
        {bn::keypad::key_type::RIGHT, 296, 1},
        {bn::keypad::key_type::L, 300, 1},
        {bn::keypad::key_type::A, 304, 1},
        {bn::keypad::key_type::L, 308, 1},
        {bn::keypad::key_type::RIGHT, 312, 1},
        {bn::keypad::key_type::L, 316, 1},
        {bn::keypad::key_type::B, 320, 1},
        {bn::keypad::key_type::L, 324, 1},
        {bn::keypad::key_type::RIGHT, 328, 1},
        {bn::keypad::key_type::L, 332, 1},
        {bn::keypad::key_type::A, 336, 1},
        {bn::keypad::key_type::L, 340, 1},
        {bn::keypad::key_type::RIGHT, 344, 1},
        {bn::keypad::key_type::L, 348, 1},
        {bn::keypad::key_type::A, 352, 1},
        {bn::keypad::key_type::A, 356, 1},
        {bn::keypad::key_type::DOWN, 360, 1},
        {bn::keypad::key_type::R, 364, 1},
        {bn::keypad::key_type::DOWN, 368, 1},
        {bn::keypad::key_type::DOWN, 372, 1},
        {bn::keypad::key_type::L, 376, 1},
        {bn::keypad::key_type::R, 380, 1},
        {bn::keypad::key_type::B, 384, 1},
        {bn::keypad::key_type::A, 388, 1},
        {bn::keypad::key_type::L, 392, 1},
        {bn::keypad::key_type::A, 396, 1},
        {bn::keypad::key_type::RIGHT, 400, 1},
        {bn::keypad::key_type::A, 404, 1},
        {bn::keypad::key_type::DOWN, 408, 1},
        {bn::keypad::key_type::R, 412, 1},
        {bn::keypad::key_type::A, 416, 1},
        {bn::keypad::key_type::A, 420, 1},
        {bn::keypad::key_type::DOWN, 424, 1},
        {bn::keypad::key_type::R, 428, 1},
        {bn::keypad::key_type::DOWN, 432, 1},
        {bn::keypad::key_type::DOWN, 436, 1},
        {bn::keypad::key_type::L, 440, 1},
        {bn::keypad::key_type::R, 444, 1},
        {bn::keypad::key_type::B, 448, 1},
        {bn::keypad::key_type::A, 452, 1},
        {bn::keypad::key_type::L, 456, 1},
        {bn::keypad::key_type::A, 460, 1},
        {bn::keypad::key_type::RIGHT, 464, 1},
        {bn::keypad::key_type::A, 468, 1},
        {bn::keypad::key_type::DOWN, 472, 1},
        {bn::keypad::key_type::R, 476, 1},
        {bn::keypad::key_type::A, 480, 1},
        {bn::keypad::key_type::A, 484, 1},
        {bn::keypad::key_type::DOWN, 488, 1},
        {bn::keypad::key_type::R, 492, 1},
        {bn::keypad::key_type::DOWN, 496, 1},
        {bn::keypad::key_type::DOWN, 500, 1},
        {bn::keypad::key_type::L, 504, 1},
        {bn::keypad::key_type::R, 508, 1},
        {bn::keypad::key_type::B, 512, 1},
        {bn::keypad::key_type::A, 516, 1},
        {bn::keypad::key_type::L, 520, 1},
        {bn::keypad::key_type::A, 524, 1},
        {bn::keypad::key_type::RIGHT, 528, 1},
        {bn::keypad::key_type::A, 532, 1},
        {bn::keypad::key_type::DOWN, 536, 1},
        {bn::keypad::key_type::R, 540, 1},
        {bn::keypad::key_type::A, 544, 1},
        {bn::keypad::key_type::A, 548, 1},
        {bn::keypad::key_type::DOWN, 552, 1},
        {bn::keypad::key_type::R, 556, 1},
        {bn::keypad::key_type::DOWN, 560, 1},
        {bn::keypad::key_type::DOWN, 564, 1},
        {bn::keypad::key_type::L, 568, 1},
        {bn::keypad::key_type::R, 572, 1},
        {bn::keypad::key_type::B, 576, 1},
        {bn::keypad::key_type::A, 580, 1},
        {bn::keypad::key_type::L, 584, 1},
        {bn::keypad::key_type::A, 588, 1},
        {bn::keypad::key_type::RIGHT, 592, 1},
        {bn::keypad::key_type::A, 596, 1},
        {bn::keypad::key_type::DOWN, 600, 1},
        {bn::keypad::key_type::R, 604, 1},
        {bn::keypad::key_type::A, 608, 1},
        {bn::keypad::key_type::L, 612, 1},
        {bn::keypad::key_type::RIGHT, 616, 1},
        {bn::keypad::key_type::L, 620, 1},
        {bn::keypad::key_type::A, 624, 1},
        {bn::keypad::key_type::L, 628, 1},
        {bn::keypad::key_type::RIGHT, 632, 1},
        {bn::keypad::key_type::L, 636, 1},
        {bn::keypad::key_type::A, 640, 1},
        {bn::keypad::key_type::L, 644, 1},
        {bn::keypad::key_type::RIGHT, 648, 1},
        {bn::keypad::key_type::L, 652, 1},
        {bn::keypad::key_type::A, 656, 1},
        {bn::keypad::key_type::L, 660, 1},
        {bn::keypad::key_type::RIGHT, 664, 1},
        {bn::keypad::key_type::L, 668, 1}
    }};

    constexpr song joan = {
        joan_data.data(),
        joan_data.size(),
        120,
        "Joan",
        normal,
        0,
        bn::music_items::a_joan
    };
    #endif

    #ifndef CODENAME_KIDS_NEXT_YEAR_OVERRIDE
    constexpr bn::array<note_data, 160> codename_kids_next_year_data = {{
        {bn::keypad::key_type::A, 32, 1},
        {bn::keypad::key_type::L, 36, 1},
        {bn::keypad::key_type::RIGHT, 40, 1},
        {bn::keypad::key_type::L, 44, 1},
        {bn::keypad::key_type::A, 48, 1},
        {bn::keypad::key_type::L, 52, 1},
        {bn::keypad::key_type::RIGHT, 56, 1},
        {bn::keypad::key_type::L, 60, 1},
        {bn::keypad::key_type::A, 64, 1},
        {bn::keypad::key_type::L, 68, 1},
        {bn::keypad::key_type::RIGHT, 72, 1},
        {bn::keypad::key_type::L, 76, 1},
        {bn::keypad::key_type::A, 80, 1},
        {bn::keypad::key_type::L, 84, 1},
        {bn::keypad::key_type::RIGHT, 88, 1},
        {bn::keypad::key_type::L, 92, 1},
        {bn::keypad::key_type::A, 96, 1},
        {bn::keypad::key_type::L, 100, 1},
        {bn::keypad::key_type::RIGHT, 104, 1},
        {bn::keypad::key_type::L, 108, 1},
        {bn::keypad::key_type::A, 112, 1},
        {bn::keypad::key_type::L, 116, 1},
        {bn::keypad::key_type::RIGHT, 120, 1},
        {bn::keypad::key_type::L, 124, 1},
        {bn::keypad::key_type::A, 128, 1},
        {bn::keypad::key_type::L, 132, 1},
        {bn::keypad::key_type::RIGHT, 136, 1},
        {bn::keypad::key_type::L, 140, 1},
        {bn::keypad::key_type::A, 144, 1},
        {bn::keypad::key_type::L, 148, 1},
        {bn::keypad::key_type::RIGHT, 152, 1},
        {bn::keypad::key_type::L, 156, 1},
        {bn::keypad::key_type::B, 160, 1},
        {bn::keypad::key_type::L, 164, 1},
        {bn::keypad::key_type::RIGHT, 168, 1},
        {bn::keypad::key_type::L, 172, 1},
        {bn::keypad::key_type::A, 176, 1},
        {bn::keypad::key_type::L, 180, 1},
        {bn::keypad::key_type::RIGHT, 184, 1},
        {bn::keypad::key_type::L, 188, 1},
        {bn::keypad::key_type::B, 192, 1},
        {bn::keypad::key_type::L, 196, 1},
        {bn::keypad::key_type::RIGHT, 200, 1},
        {bn::keypad::key_type::L, 204, 1},
        {bn::keypad::key_type::A, 208, 1},
        {bn::keypad::key_type::L, 212, 1},
        {bn::keypad::key_type::RIGHT, 216, 1},
        {bn::keypad::key_type::L, 220, 1},
        {bn::keypad::key_type::A, 224, 1},
        {bn::keypad::key_type::L, 228, 1},
        {bn::keypad::key_type::RIGHT, 232, 1},
        {bn::keypad::key_type::L, 236, 1},
        {bn::keypad::key_type::A, 240, 1},
        {bn::keypad::key_type::L, 244, 1},
        {bn::keypad::key_type::RIGHT, 248, 1},
        {bn::keypad::key_type::L, 252, 1},
        {bn::keypad::key_type::A, 256, 1},
        {bn::keypad::key_type::L, 260, 1},
        {bn::keypad::key_type::RIGHT, 264, 1},
        {bn::keypad::key_type::L, 268, 1},
        {bn::keypad::key_type::A, 272, 1},
        {bn::keypad::key_type::L, 276, 1},
        {bn::keypad::key_type::RIGHT, 280, 1},
        {bn::keypad::key_type::L, 284, 1},
        {bn::keypad::key_type::B, 288, 1},
        {bn::keypad::key_type::L, 292, 1},
        {bn::keypad::key_type::RIGHT, 296, 1},
        {bn::keypad::key_type::L, 300, 1},
        {bn::keypad::key_type::A, 304, 1},
        {bn::keypad::key_type::L, 308, 1},
        {bn::keypad::key_type::RIGHT, 312, 1},
        {bn::keypad::key_type::L, 316, 1},
        {bn::keypad::key_type::B, 320, 1},
        {bn::keypad::key_type::L, 324, 1},
        {bn::keypad::key_type::RIGHT, 328, 1},
        {bn::keypad::key_type::L, 332, 1},
        {bn::keypad::key_type::A, 336, 1},
        {bn::keypad::key_type::L, 340, 1},
        {bn::keypad::key_type::RIGHT, 344, 1},
        {bn::keypad::key_type::L, 348, 1},
        {bn::keypad::key_type::A, 352, 1},
        {bn::keypad::key_type::A, 356, 1},
        {bn::keypad::key_type::DOWN, 360, 1},
        {bn::keypad::key_type::R, 364, 1},
        {bn::keypad::key_type::DOWN, 368, 1},
        {bn::keypad::key_type::DOWN, 372, 1},
        {bn::keypad::key_type::L, 376, 1},
        {bn::keypad::key_type::R, 380, 1},
        {bn::keypad::key_type::B, 384, 1},
        {bn::keypad::key_type::A, 388, 1},
        {bn::keypad::key_type::L, 392, 1},
        {bn::keypad::key_type::A, 396, 1},
        {bn::keypad::key_type::RIGHT, 400, 1},
        {bn::keypad::key_type::A, 404, 1},
        {bn::keypad::key_type::DOWN, 408, 1},
        {bn::keypad::key_type::R, 412, 1},
        {bn::keypad::key_type::A, 416, 1},
        {bn::keypad::key_type::A, 420, 1},
        {bn::keypad::key_type::DOWN, 424, 1},
        {bn::keypad::key_type::R, 428, 1},
        {bn::keypad::key_type::DOWN, 432, 1},
        {bn::keypad::key_type::DOWN, 436, 1},
        {bn::keypad::key_type::L, 440, 1},
        {bn::keypad::key_type::R, 444, 1},
        {bn::keypad::key_type::B, 448, 1},
        {bn::keypad::key_type::A, 452, 1},
        {bn::keypad::key_type::L, 456, 1},
        {bn::keypad::key_type::A, 460, 1},
        {bn::keypad::key_type::RIGHT, 464, 1},
        {bn::keypad::key_type::A, 468, 1},
        {bn::keypad::key_type::DOWN, 472, 1},
        {bn::keypad::key_type::R, 476, 1},
        {bn::keypad::key_type::A, 480, 1},
        {bn::keypad::key_type::A, 484, 1},
        {bn::keypad::key_type::DOWN, 488, 1},
        {bn::keypad::key_type::R, 492, 1},
        {bn::keypad::key_type::DOWN, 496, 1},
        {bn::keypad::key_type::DOWN, 500, 1},
        {bn::keypad::key_type::L, 504, 1},
        {bn::keypad::key_type::R, 508, 1},
        {bn::keypad::key_type::B, 512, 1},
        {bn::keypad::key_type::A, 516, 1},
        {bn::keypad::key_type::L, 520, 1},
        {bn::keypad::key_type::A, 524, 1},
        {bn::keypad::key_type::RIGHT, 528, 1},
        {bn::keypad::key_type::A, 532, 1},
        {bn::keypad::key_type::DOWN, 536, 1},
        {bn::keypad::key_type::R, 540, 1},
        {bn::keypad::key_type::A, 544, 1},
        {bn::keypad::key_type::A, 548, 1},
        {bn::keypad::key_type::DOWN, 552, 1},
        {bn::keypad::key_type::R, 556, 1},
        {bn::keypad::key_type::DOWN, 560, 1},
        {bn::keypad::key_type::DOWN, 564, 1},
        {bn::keypad::key_type::L, 568, 1},
        {bn::keypad::key_type::R, 572, 1},
        {bn::keypad::key_type::B, 576, 1},
        {bn::keypad::key_type::A, 580, 1},
        {bn::keypad::key_type::L, 584, 1},
        {bn::keypad::key_type::A, 588, 1},
        {bn::keypad::key_type::RIGHT, 592, 1},
        {bn::keypad::key_type::A, 596, 1},
        {bn::keypad::key_type::DOWN, 600, 1},
        {bn::keypad::key_type::R, 604, 1},
        {bn::keypad::key_type::A, 608, 1},
        {bn::keypad::key_type::L, 612, 1},
        {bn::keypad::key_type::RIGHT, 616, 1},
        {bn::keypad::key_type::L, 620, 1},
        {bn::keypad::key_type::A, 624, 1},
        {bn::keypad::key_type::L, 628, 1},
        {bn::keypad::key_type::RIGHT, 632, 1},
        {bn::keypad::key_type::L, 636, 1},
        {bn::keypad::key_type::A, 640, 1},
        {bn::keypad::key_type::L, 644, 1},
        {bn::keypad::key_type::RIGHT, 648, 1},
        {bn::keypad::key_type::L, 652, 1},
        {bn::keypad::key_type::A, 656, 1},
        {bn::keypad::key_type::L, 660, 1},
        {bn::keypad::key_type::RIGHT, 664, 1},
        {bn::keypad::key_type::L, 668, 1}
    }};

    constexpr song codename_kids_next_year = {
        codename_kids_next_year_data.data(),
        codename_kids_next_year_data.size(),
        120,
        "Codename Kids Next Year",
        normal,
        1,
        bn::music_items::b_codename_kids_next_year
    };
    #endif

    constexpr bn::array<const song*, 3> all_songs = {{
        &fastest_kid_alive,
        &joan,
        &codename_kids_next_year
    }};
}
#endif