#ifndef SONGS_H
#define SONGS_H

#include "bn_array.h"
#include "bn_keypad.h"

#include "note.h"

namespace songs
{
    struct song {
        const note_data* notes; // Pointer to the first element of the array of notes
        int size; // Number of notes in the song
        int tempo;
        const char* name; // Name of the song - displayed in menus
    };

    constexpr bn::array<note_data, 160> test_song_data = {{
        {bn::keypad::key_type::A, 32, 1, normal},
        {bn::keypad::key_type::L, 36, 1, normal},
        {bn::keypad::key_type::R, 40, 1, normal},
        {bn::keypad::key_type::L, 44, 1, normal},
        {bn::keypad::key_type::A, 48, 1, normal},
        {bn::keypad::key_type::L, 52, 1, normal},
        {bn::keypad::key_type::R, 56, 1, normal},
        {bn::keypad::key_type::L, 60, 1, normal},
        {bn::keypad::key_type::A, 64, 1, normal},
        {bn::keypad::key_type::L, 68, 1, normal},
        {bn::keypad::key_type::R, 72, 1, normal},
        {bn::keypad::key_type::L, 76, 1, normal},
        {bn::keypad::key_type::A, 80, 1, normal},
        {bn::keypad::key_type::L, 84, 1, normal},
        {bn::keypad::key_type::R, 88, 1, normal},
        {bn::keypad::key_type::L, 92, 1, normal},
        {bn::keypad::key_type::A, 96, 1, normal},
        {bn::keypad::key_type::L, 100, 1, normal},
        {bn::keypad::key_type::R, 104, 1, normal},
        {bn::keypad::key_type::L, 108, 1, normal},
        {bn::keypad::key_type::A, 112, 1, normal},
        {bn::keypad::key_type::L, 116, 1, normal},
        {bn::keypad::key_type::R, 120, 1, normal},
        {bn::keypad::key_type::L, 124, 1, normal},
        {bn::keypad::key_type::A, 128, 1, normal},
        {bn::keypad::key_type::L, 132, 1, normal},
        {bn::keypad::key_type::R, 136, 1, normal},
        {bn::keypad::key_type::L, 140, 1, normal},
        {bn::keypad::key_type::A, 144, 1, normal},
        {bn::keypad::key_type::L, 148, 1, normal},
        {bn::keypad::key_type::R, 152, 1, normal},
        {bn::keypad::key_type::L, 156, 1, normal},
        {bn::keypad::key_type::B, 160, 1, normal},
        {bn::keypad::key_type::L, 164, 1, normal},
        {bn::keypad::key_type::R, 168, 1, normal},
        {bn::keypad::key_type::L, 172, 1, normal},
        {bn::keypad::key_type::A, 176, 1, normal},
        {bn::keypad::key_type::L, 180, 1, normal},
        {bn::keypad::key_type::R, 184, 1, normal},
        {bn::keypad::key_type::L, 188, 1, normal},
        {bn::keypad::key_type::B, 192, 1, normal},
        {bn::keypad::key_type::L, 196, 1, normal},
        {bn::keypad::key_type::R, 200, 1, normal},
        {bn::keypad::key_type::L, 204, 1, normal},
        {bn::keypad::key_type::A, 208, 1, normal},
        {bn::keypad::key_type::L, 212, 1, normal},
        {bn::keypad::key_type::R, 216, 1, normal},
        {bn::keypad::key_type::L, 220, 1, normal},
        {bn::keypad::key_type::A, 224, 1, normal},
        {bn::keypad::key_type::L, 228, 1, normal},
        {bn::keypad::key_type::R, 232, 1, normal},
        {bn::keypad::key_type::L, 236, 1, normal},
        {bn::keypad::key_type::A, 240, 1, normal},
        {bn::keypad::key_type::L, 244, 1, normal},
        {bn::keypad::key_type::R, 248, 1, normal},
        {bn::keypad::key_type::L, 252, 1, normal},
        {bn::keypad::key_type::A, 256, 1, normal},
        {bn::keypad::key_type::L, 260, 1, normal},
        {bn::keypad::key_type::R, 264, 1, normal},
        {bn::keypad::key_type::L, 268, 1, normal},
        {bn::keypad::key_type::A, 272, 1, normal},
        {bn::keypad::key_type::L, 276, 1, normal},
        {bn::keypad::key_type::R, 280, 1, normal},
        {bn::keypad::key_type::L, 284, 1, normal},
        {bn::keypad::key_type::B, 288, 1, normal},
        {bn::keypad::key_type::L, 292, 1, normal},
        {bn::keypad::key_type::R, 296, 1, normal},
        {bn::keypad::key_type::L, 300, 1, normal},
        {bn::keypad::key_type::A, 304, 1, normal},
        {bn::keypad::key_type::L, 308, 1, normal},
        {bn::keypad::key_type::R, 312, 1, normal},
        {bn::keypad::key_type::L, 316, 1, normal},
        {bn::keypad::key_type::B, 320, 1, normal},
        {bn::keypad::key_type::L, 324, 1, normal},
        {bn::keypad::key_type::R, 328, 1, normal},
        {bn::keypad::key_type::L, 332, 1, normal},
        {bn::keypad::key_type::A, 336, 1, normal},
        {bn::keypad::key_type::L, 340, 1, normal},
        {bn::keypad::key_type::R, 344, 1, normal},
        {bn::keypad::key_type::L, 348, 1, normal},
        {bn::keypad::key_type::A, 352, 1, normal},
        {bn::keypad::key_type::A, 356, 1, normal},
        {bn::keypad::key_type::DOWN, 360, 1, normal},
        {bn::keypad::key_type::R, 364, 1, normal},
        {bn::keypad::key_type::DOWN, 368, 1, normal},
        {bn::keypad::key_type::DOWN, 372, 1, normal},
        {bn::keypad::key_type::L, 376, 1, normal},
        {bn::keypad::key_type::R, 380, 1, normal},
        {bn::keypad::key_type::B, 384, 1, normal},
        {bn::keypad::key_type::A, 388, 1, normal},
        {bn::keypad::key_type::L, 392, 1, normal},
        {bn::keypad::key_type::A, 396, 1, normal},
        {bn::keypad::key_type::R, 400, 1, normal},
        {bn::keypad::key_type::A, 404, 1, normal},
        {bn::keypad::key_type::DOWN, 408, 1, normal},
        {bn::keypad::key_type::R, 412, 1, normal},
        {bn::keypad::key_type::A, 416, 1, normal},
        {bn::keypad::key_type::A, 420, 1, normal},
        {bn::keypad::key_type::DOWN, 424, 1, normal},
        {bn::keypad::key_type::R, 428, 1, normal},
        {bn::keypad::key_type::DOWN, 432, 1, normal},
        {bn::keypad::key_type::DOWN, 436, 1, normal},
        {bn::keypad::key_type::L, 440, 1, normal},
        {bn::keypad::key_type::R, 444, 1, normal},
        {bn::keypad::key_type::B, 448, 1, normal},
        {bn::keypad::key_type::A, 452, 1, normal},
        {bn::keypad::key_type::L, 456, 1, normal},
        {bn::keypad::key_type::A, 460, 1, normal},
        {bn::keypad::key_type::R, 464, 1, normal},
        {bn::keypad::key_type::A, 468, 1, normal},
        {bn::keypad::key_type::DOWN, 472, 1, normal},
        {bn::keypad::key_type::R, 476, 1, normal},
        {bn::keypad::key_type::A, 480, 1, normal},
        {bn::keypad::key_type::A, 484, 1, normal},
        {bn::keypad::key_type::DOWN, 488, 1, normal},
        {bn::keypad::key_type::R, 492, 1, normal},
        {bn::keypad::key_type::DOWN, 496, 1, normal},
        {bn::keypad::key_type::DOWN, 500, 1, normal},
        {bn::keypad::key_type::L, 504, 1, normal},
        {bn::keypad::key_type::R, 508, 1, normal},
        {bn::keypad::key_type::B, 512, 1, normal},
        {bn::keypad::key_type::A, 516, 1, normal},
        {bn::keypad::key_type::L, 520, 1, normal},
        {bn::keypad::key_type::A, 524, 1, normal},
        {bn::keypad::key_type::R, 528, 1, normal},
        {bn::keypad::key_type::A, 532, 1, normal},
        {bn::keypad::key_type::DOWN, 536, 1, normal},
        {bn::keypad::key_type::R, 540, 1, normal},
        {bn::keypad::key_type::A, 544, 1, normal},
        {bn::keypad::key_type::A, 548, 1, normal},
        {bn::keypad::key_type::DOWN, 552, 1, normal},
        {bn::keypad::key_type::R, 556, 1, normal},
        {bn::keypad::key_type::DOWN, 560, 1, normal},
        {bn::keypad::key_type::DOWN, 564, 1, normal},
        {bn::keypad::key_type::L, 568, 1, normal},
        {bn::keypad::key_type::R, 572, 1, normal},
        {bn::keypad::key_type::B, 576, 1, normal},
        {bn::keypad::key_type::A, 580, 1, normal},
        {bn::keypad::key_type::L, 584, 1, normal},
        {bn::keypad::key_type::A, 588, 1, normal},
        {bn::keypad::key_type::R, 592, 1, normal},
        {bn::keypad::key_type::A, 596, 1, normal},
        {bn::keypad::key_type::DOWN, 600, 1, normal},
        {bn::keypad::key_type::R, 604, 1, normal},
        {bn::keypad::key_type::A, 608, 1, normal},
        {bn::keypad::key_type::L, 612, 1, normal},
        {bn::keypad::key_type::R, 616, 1, normal},
        {bn::keypad::key_type::L, 620, 1, normal},
        {bn::keypad::key_type::A, 624, 1, normal},
        {bn::keypad::key_type::L, 628, 1, normal},
        {bn::keypad::key_type::R, 632, 1, normal},
        {bn::keypad::key_type::L, 636, 1, normal},
        {bn::keypad::key_type::A, 640, 1, normal},
        {bn::keypad::key_type::L, 644, 1, normal},
        {bn::keypad::key_type::R, 648, 1, normal},
        {bn::keypad::key_type::L, 652, 1, normal},
        {bn::keypad::key_type::A, 656, 1, normal},
        {bn::keypad::key_type::L, 660, 1, normal},
        {bn::keypad::key_type::R, 664, 1, normal},
        {bn::keypad::key_type::L, 668, 1, normal}
    }};

    constexpr song test_song = {
        test_song_data.data(),
        test_song_data.size(),
        120,
        "Test Song"
    };
}

#endif // SONGS_H